/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/codes.proto */

#ifndef PROTOBUF_C_yoke_2fplugin_2fv1_2fcodes_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2fplugin_2fv1_2fcodes_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/descriptor.pb-c.h"



/* --- enums --- */

typedef enum _Yoke__Plugin__V1__Code {
  YOKE__PLUGIN__V1__CODE__CODE_UNSPECIFIED = 0,
  /*
   * The request does not decode, or a required field is absent.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_STRUCTURAL_MALFORMED = 1,
  /*
   * The Registry has no such plugin.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN = 2,
  /*
   * No document composes this unit.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT = 3,
  /*
   * An operator disabled the plugin.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_STATE_DISABLED = 4,
  /*
   * The token is not this Core's, or not for this pair.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_AUTH_INVALID = 5,
  /*
   * The startup window has passed.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_AUTH_EXPIRED = 6,
  /*
   * The token has already been spent.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_AUTH_CONSUMED = 7,
  /*
   * The protocol version is absent, or this Core does not support it.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_COMPAT_UNSUPPORTED = 8,
  /*
   * The process describes itself differently from its Manifest.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_CONSISTENCY_DIVERGENT = 9,
  /*
   * This unit is already live.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_CONFLICT_UNIT_LIVE = 10,
  /*
   * The acceptance could not be turned into an enforceable Session.
   */
  YOKE__PLUGIN__V1__CODE__CODE_ADMISSION_SESSION_UNAVAILABLE = 11,
  /*
   * The identity in a first envelope was never issued, is already used, or has ended.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_UNKNOWN = 12,
  /*
   * The Session ended before this message arrived.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_REVOKED = 13,
  /*
   * An envelope carries no payload, or a field exceeds its bound.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_MESSAGE_MALFORMED = 14,
  /*
   * A message identity repeated within one Session.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_MESSAGE_DUPLICATE = 15,
  /*
   * A family arrived from the side that may not originate it.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_DIRECTION = 16,
  /*
   * A family that must correlate did not.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_CORRELATION_MISSING = 17,
  /*
   * A correlation names no message in this Session.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SESSION_CORRELATION_UNKNOWN = 18,
  /*
   * The operation names something declared but not authorised.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SCOPE_WITHHELD = 19,
  /*
   * It names something the process never declared.
   */
  YOKE__PLUGIN__V1__CODE__CODE_SCOPE_UNDECLARED = 20,
  /*
   * Data arrived for a stream that is not activated.
   */
  YOKE__PLUGIN__V1__CODE__CODE_STREAM_INACTIVE = 21,
  /*
   * An acknowledgement names a command that was never issued.
   */
  YOKE__PLUGIN__V1__CODE__CODE_COMMAND_UNKNOWN = 22,
  /*
   * A response names a question that was never asked.
   */
  YOKE__PLUGIN__V1__CODE__CODE_QUERY_UNKNOWN = 23
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__CODE)
} Yoke__Plugin__V1__Code;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    yoke__plugin__v1__code__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2fplugin_2fv1_2fcodes_2eproto__INCLUDED */
