/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/contract.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/plugin/v1/contract.pb-c.h"
static const ProtobufCEnumValue yoke__plugin__v1__contract__enum_values_by_number[2] =
{
  { "CONTRACT_UNSPECIFIED", "YOKE__PLUGIN__V1__CONTRACT__CONTRACT_UNSPECIFIED", 0 },
  { "CONTRACT_VERSION", "YOKE__PLUGIN__V1__CONTRACT__CONTRACT_VERSION", 1 },
};
static const ProtobufCIntRange yoke__plugin__v1__contract__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__contract__enum_values_by_name[2] =
{
  { "CONTRACT_UNSPECIFIED", 0 },
  { "CONTRACT_VERSION", 1 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__contract__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Contract",
  "Contract",
  "Yoke__Plugin__V1__Contract",
  "yoke.plugin.v1",
  2,
  yoke__plugin__v1__contract__enum_values_by_number,
  2,
  yoke__plugin__v1__contract__enum_values_by_name,
  1,
  yoke__plugin__v1__contract__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
