/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/families.proto */

#ifndef PROTOBUF_C_yoke_2fplugin_2fv1_2ffamilies_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2fplugin_2fv1_2ffamilies_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Yoke__Plugin__V1__SessionMessage Yoke__Plugin__V1__SessionMessage;
typedef struct Yoke__Plugin__V1__SessionMessage__Open Yoke__Plugin__V1__SessionMessage__Open;
typedef struct Yoke__Plugin__V1__SessionMessage__Close Yoke__Plugin__V1__SessionMessage__Close;
typedef struct Yoke__Plugin__V1__SessionMessage__Revoked Yoke__Plugin__V1__SessionMessage__Revoked;
typedef struct Yoke__Plugin__V1__Control Yoke__Plugin__V1__Control;
typedef struct Yoke__Plugin__V1__Control__Command Yoke__Plugin__V1__Control__Command;
typedef struct Yoke__Plugin__V1__Control__Activate Yoke__Plugin__V1__Control__Activate;
typedef struct Yoke__Plugin__V1__Control__Stop Yoke__Plugin__V1__Control__Stop;
typedef struct Yoke__Plugin__V1__Ack Yoke__Plugin__V1__Ack;
typedef struct Yoke__Plugin__V1__Query Yoke__Plugin__V1__Query;
typedef struct Yoke__Plugin__V1__Query__Question Yoke__Plugin__V1__Query__Question;
typedef struct Yoke__Plugin__V1__Query__Answer Yoke__Plugin__V1__Query__Answer;
typedef struct Yoke__Plugin__V1__Data Yoke__Plugin__V1__Data;
typedef struct Yoke__Plugin__V1__Health Yoke__Plugin__V1__Health;
typedef struct Yoke__Plugin__V1__Event Yoke__Plugin__V1__Event;
typedef struct Yoke__Plugin__V1__Error Yoke__Plugin__V1__Error;
typedef struct Yoke__Plugin__V1__Error__Divergence Yoke__Plugin__V1__Error__Divergence;
typedef struct Yoke__Plugin__V1__Error__Withheld Yoke__Plugin__V1__Error__Withheld;


/* --- enums --- */

typedef enum _Yoke__Plugin__V1__SessionMessage__Revoked__Cause {
  YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_UNSPECIFIED = 0,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_LIVENESS_LOST = 1,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_PLUGIN_DISABLED = 2,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_SCOPE_EXCEEDED = 3,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_PROTOCOL_FAILURE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE)
} Yoke__Plugin__V1__SessionMessage__Revoked__Cause;
typedef enum _Yoke__Plugin__V1__Control__Activate__Transport {
  YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_UNSPECIFIED = 0,
  YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_ORDERED = 1,
  YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_FRAMED = 2,
  YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_SHARED_OBJECT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT)
} Yoke__Plugin__V1__Control__Activate__Transport;
typedef enum _Yoke__Plugin__V1__Ack__Outcome {
  YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_UNSPECIFIED = 0,
  YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_ACCEPTED = 1,
  YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_DONE = 2,
  YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_FAILED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__ACK__OUTCOME)
} Yoke__Plugin__V1__Ack__Outcome;

/* --- messages --- */

/*
 * The first envelope on the stream, from the unit.
 */
struct  Yoke__Plugin__V1__SessionMessage__Open
{
  ProtobufCMessage base;
};
#define YOKE__PLUGIN__V1__SESSION_MESSAGE__OPEN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__session_message__open__descriptor) \
     }


/*
 * The unit's orderly departure.
 */
struct  Yoke__Plugin__V1__SessionMessage__Close
{
  ProtobufCMessage base;
};
#define YOKE__PLUGIN__V1__SESSION_MESSAGE__CLOSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__session_message__close__descriptor) \
     }


/*
 * The Core ending the Session, and why.
 */
struct  Yoke__Plugin__V1__SessionMessage__Revoked
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__SessionMessage__Revoked__Cause cause;
  char *line;
};
#define YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__session_message__revoked__descriptor) \
    , YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_UNSPECIFIED, (char *)protobuf_c_empty_string }


typedef enum {
  YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND__NOT_SET = 0,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND_OPEN = 1,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND_CLOSE = 2,
  YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND_REVOKED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND__CASE)
} Yoke__Plugin__V1__SessionMessage__KindCase;

struct  Yoke__Plugin__V1__SessionMessage
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__SessionMessage__KindCase kind_case;
  union {
    Yoke__Plugin__V1__SessionMessage__Open *open;
    Yoke__Plugin__V1__SessionMessage__Close *close;
    Yoke__Plugin__V1__SessionMessage__Revoked *revoked;
  };
};
#define YOKE__PLUGIN__V1__SESSION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__session_message__descriptor) \
    , YOKE__PLUGIN__V1__SESSION_MESSAGE__KIND__NOT_SET, {0} }


/*
 * A command type the unit declared, and its payload.
 */
struct  Yoke__Plugin__V1__Control__Command
{
  ProtobufCMessage base;
  char *type;
  ProtobufCBinaryData payload;
};
#define YOKE__PLUGIN__V1__CONTROL__COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__control__command__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


/*
 * A stream's activation: what the unit connects to, and how it frames what it sends.
 */
struct  Yoke__Plugin__V1__Control__Activate
{
  ProtobufCMessage base;
  char *stream;
  Yoke__Plugin__V1__Control__Activate__Transport transport;
  char *address;
};
#define YOKE__PLUGIN__V1__CONTROL__ACTIVATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__control__activate__descriptor) \
    , (char *)protobuf_c_empty_string, YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_UNSPECIFIED, (char *)protobuf_c_empty_string }


/*
 * The instruction that stops a stream.
 */
struct  Yoke__Plugin__V1__Control__Stop
{
  ProtobufCMessage base;
  char *stream;
};
#define YOKE__PLUGIN__V1__CONTROL__STOP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__control__stop__descriptor) \
    , (char *)protobuf_c_empty_string }


typedef enum {
  YOKE__PLUGIN__V1__CONTROL__KIND__NOT_SET = 0,
  YOKE__PLUGIN__V1__CONTROL__KIND_COMMAND = 1,
  YOKE__PLUGIN__V1__CONTROL__KIND_ACTIVATE = 2,
  YOKE__PLUGIN__V1__CONTROL__KIND_STOP = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__CONTROL__KIND__CASE)
} Yoke__Plugin__V1__Control__KindCase;

/*
 * From the Core: what this unit should do.
 */
struct  Yoke__Plugin__V1__Control
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__Control__KindCase kind_case;
  union {
    Yoke__Plugin__V1__Control__Command *command;
    Yoke__Plugin__V1__Control__Activate *activate;
    Yoke__Plugin__V1__Control__Stop *stop;
  };
};
#define YOKE__PLUGIN__V1__CONTROL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__control__descriptor) \
    , YOKE__PLUGIN__V1__CONTROL__KIND__NOT_SET, {0} }


/*
 * From the unit, correlated: what became of that instruction. An acceptance is followed by at most one
 * final answer, and no acknowledgement carries a domain result.
 */
struct  Yoke__Plugin__V1__Ack
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__Ack__Outcome outcome;
  char *line;
};
#define YOKE__PLUGIN__V1__ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__ack__descriptor) \
    , YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_UNSPECIFIED, (char *)protobuf_c_empty_string }


struct  Yoke__Plugin__V1__Query__Question
{
  ProtobufCMessage base;
  char *type;
  ProtobufCBinaryData payload;
};
#define YOKE__PLUGIN__V1__QUERY__QUESTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__query__question__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


struct  Yoke__Plugin__V1__Query__Answer
{
  ProtobufCMessage base;
  ProtobufCBinaryData payload;
};
#define YOKE__PLUGIN__V1__QUERY__ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__query__answer__descriptor) \
    , {0,NULL} }


typedef enum {
  YOKE__PLUGIN__V1__QUERY__KIND__NOT_SET = 0,
  YOKE__PLUGIN__V1__QUERY__KIND_QUESTION = 1,
  YOKE__PLUGIN__V1__QUERY__KIND_ANSWER = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__QUERY__KIND__CASE)
} Yoke__Plugin__V1__Query__KindCase;

/*
 * A question from the Core, and the unit's answer, correlated to it.
 */
struct  Yoke__Plugin__V1__Query
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__Query__KindCase kind_case;
  union {
    Yoke__Plugin__V1__Query__Question *question;
    Yoke__Plugin__V1__Query__Answer *answer;
  };
};
#define YOKE__PLUGIN__V1__QUERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__query__descriptor) \
    , YOKE__PLUGIN__V1__QUERY__KIND__NOT_SET, {0} }


/*
 * What a stream produces. Never on the Session: only on its own ordered transport, which names the
 * stream. The sequence is per stream, from 1, never reused within an activation.
 */
struct  Yoke__Plugin__V1__Data
{
  ProtobufCMessage base;
  uint64_t sequence;
  ProtobufCBinaryData payload;
};
#define YOKE__PLUGIN__V1__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__data__descriptor) \
    , 0, {0,NULL} }


/*
 * Alive, and how well: a grade from 0 to 99, and a line.
 */
struct  Yoke__Plugin__V1__Health
{
  ProtobufCMessage base;
  uint32_t grade;
  char *line;
};
#define YOKE__PLUGIN__V1__HEALTH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__health__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


/*
 * What just happened: a class the unit declared and was granted, a severity from 0 to 99 the unit
 * declares, a line, and a detail the Core carries into the event unchanged.
 */
struct  Yoke__Plugin__V1__Event
{
  ProtobufCMessage base;
  char *occurrence;
  uint32_t severity;
  char *line;
  ProtobufCBinaryData detail;
};
#define YOKE__PLUGIN__V1__EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__event__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, {0,NULL} }


/*
 * Each item that differs between a process and its Manifest.
 */
struct  Yoke__Plugin__V1__Error__Divergence
{
  ProtobufCMessage base;
  size_t n_items;
  char **items;
};
#define YOKE__PLUGIN__V1__ERROR__DIVERGENCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__error__divergence__descriptor) \
    , 0,NULL }


/*
 * The item declared and not authorised.
 */
struct  Yoke__Plugin__V1__Error__Withheld
{
  ProtobufCMessage base;
  char *item;
};
#define YOKE__PLUGIN__V1__ERROR__WITHHELD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__error__withheld__descriptor) \
    , (char *)protobuf_c_empty_string }


typedef enum {
  YOKE__PLUGIN__V1__ERROR__DETAIL__NOT_SET = 0,
  YOKE__PLUGIN__V1__ERROR__DETAIL_DIVERGENT = 3,
  YOKE__PLUGIN__V1__ERROR__DETAIL_WITHHELD = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__ERROR__DETAIL__CASE)
} Yoke__Plugin__V1__Error__DetailCase;

/*
 * What went wrong: a code, one of Code's names; a message for a person; a detail typed per code.
 */
struct  Yoke__Plugin__V1__Error
{
  ProtobufCMessage base;
  char *code;
  char *message;
  Yoke__Plugin__V1__Error__DetailCase detail_case;
  union {
    Yoke__Plugin__V1__Error__Divergence *divergent;
    Yoke__Plugin__V1__Error__Withheld *withheld;
  };
};
#define YOKE__PLUGIN__V1__ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__error__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, YOKE__PLUGIN__V1__ERROR__DETAIL__NOT_SET, {0} }


/* Yoke__Plugin__V1__SessionMessage__Open methods */
void   yoke__plugin__v1__session_message__open__init
                     (Yoke__Plugin__V1__SessionMessage__Open         *message);
/* Yoke__Plugin__V1__SessionMessage__Close methods */
void   yoke__plugin__v1__session_message__close__init
                     (Yoke__Plugin__V1__SessionMessage__Close         *message);
/* Yoke__Plugin__V1__SessionMessage__Revoked methods */
void   yoke__plugin__v1__session_message__revoked__init
                     (Yoke__Plugin__V1__SessionMessage__Revoked         *message);
/* Yoke__Plugin__V1__SessionMessage methods */
void   yoke__plugin__v1__session_message__init
                     (Yoke__Plugin__V1__SessionMessage         *message);
size_t yoke__plugin__v1__session_message__get_packed_size
                     (const Yoke__Plugin__V1__SessionMessage   *message);
size_t yoke__plugin__v1__session_message__pack
                     (const Yoke__Plugin__V1__SessionMessage   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__session_message__pack_to_buffer
                     (const Yoke__Plugin__V1__SessionMessage   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__SessionMessage *
       yoke__plugin__v1__session_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__session_message__free_unpacked
                     (Yoke__Plugin__V1__SessionMessage *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Control__Command methods */
void   yoke__plugin__v1__control__command__init
                     (Yoke__Plugin__V1__Control__Command         *message);
/* Yoke__Plugin__V1__Control__Activate methods */
void   yoke__plugin__v1__control__activate__init
                     (Yoke__Plugin__V1__Control__Activate         *message);
/* Yoke__Plugin__V1__Control__Stop methods */
void   yoke__plugin__v1__control__stop__init
                     (Yoke__Plugin__V1__Control__Stop         *message);
/* Yoke__Plugin__V1__Control methods */
void   yoke__plugin__v1__control__init
                     (Yoke__Plugin__V1__Control         *message);
size_t yoke__plugin__v1__control__get_packed_size
                     (const Yoke__Plugin__V1__Control   *message);
size_t yoke__plugin__v1__control__pack
                     (const Yoke__Plugin__V1__Control   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__control__pack_to_buffer
                     (const Yoke__Plugin__V1__Control   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Control *
       yoke__plugin__v1__control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__control__free_unpacked
                     (Yoke__Plugin__V1__Control *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Ack methods */
void   yoke__plugin__v1__ack__init
                     (Yoke__Plugin__V1__Ack         *message);
size_t yoke__plugin__v1__ack__get_packed_size
                     (const Yoke__Plugin__V1__Ack   *message);
size_t yoke__plugin__v1__ack__pack
                     (const Yoke__Plugin__V1__Ack   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__ack__pack_to_buffer
                     (const Yoke__Plugin__V1__Ack   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Ack *
       yoke__plugin__v1__ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__ack__free_unpacked
                     (Yoke__Plugin__V1__Ack *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Query__Question methods */
void   yoke__plugin__v1__query__question__init
                     (Yoke__Plugin__V1__Query__Question         *message);
/* Yoke__Plugin__V1__Query__Answer methods */
void   yoke__plugin__v1__query__answer__init
                     (Yoke__Plugin__V1__Query__Answer         *message);
/* Yoke__Plugin__V1__Query methods */
void   yoke__plugin__v1__query__init
                     (Yoke__Plugin__V1__Query         *message);
size_t yoke__plugin__v1__query__get_packed_size
                     (const Yoke__Plugin__V1__Query   *message);
size_t yoke__plugin__v1__query__pack
                     (const Yoke__Plugin__V1__Query   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__query__pack_to_buffer
                     (const Yoke__Plugin__V1__Query   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Query *
       yoke__plugin__v1__query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__query__free_unpacked
                     (Yoke__Plugin__V1__Query *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Data methods */
void   yoke__plugin__v1__data__init
                     (Yoke__Plugin__V1__Data         *message);
size_t yoke__plugin__v1__data__get_packed_size
                     (const Yoke__Plugin__V1__Data   *message);
size_t yoke__plugin__v1__data__pack
                     (const Yoke__Plugin__V1__Data   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__data__pack_to_buffer
                     (const Yoke__Plugin__V1__Data   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Data *
       yoke__plugin__v1__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__data__free_unpacked
                     (Yoke__Plugin__V1__Data *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Health methods */
void   yoke__plugin__v1__health__init
                     (Yoke__Plugin__V1__Health         *message);
size_t yoke__plugin__v1__health__get_packed_size
                     (const Yoke__Plugin__V1__Health   *message);
size_t yoke__plugin__v1__health__pack
                     (const Yoke__Plugin__V1__Health   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__health__pack_to_buffer
                     (const Yoke__Plugin__V1__Health   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Health *
       yoke__plugin__v1__health__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__health__free_unpacked
                     (Yoke__Plugin__V1__Health *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Event methods */
void   yoke__plugin__v1__event__init
                     (Yoke__Plugin__V1__Event         *message);
size_t yoke__plugin__v1__event__get_packed_size
                     (const Yoke__Plugin__V1__Event   *message);
size_t yoke__plugin__v1__event__pack
                     (const Yoke__Plugin__V1__Event   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__event__pack_to_buffer
                     (const Yoke__Plugin__V1__Event   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Event *
       yoke__plugin__v1__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__event__free_unpacked
                     (Yoke__Plugin__V1__Event *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Error__Divergence methods */
void   yoke__plugin__v1__error__divergence__init
                     (Yoke__Plugin__V1__Error__Divergence         *message);
/* Yoke__Plugin__V1__Error__Withheld methods */
void   yoke__plugin__v1__error__withheld__init
                     (Yoke__Plugin__V1__Error__Withheld         *message);
/* Yoke__Plugin__V1__Error methods */
void   yoke__plugin__v1__error__init
                     (Yoke__Plugin__V1__Error         *message);
size_t yoke__plugin__v1__error__get_packed_size
                     (const Yoke__Plugin__V1__Error   *message);
size_t yoke__plugin__v1__error__pack
                     (const Yoke__Plugin__V1__Error   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__error__pack_to_buffer
                     (const Yoke__Plugin__V1__Error   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Error *
       yoke__plugin__v1__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__error__free_unpacked
                     (Yoke__Plugin__V1__Error *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Plugin__V1__SessionMessage__Open_Closure)
                 (const Yoke__Plugin__V1__SessionMessage__Open *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__SessionMessage__Close_Closure)
                 (const Yoke__Plugin__V1__SessionMessage__Close *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__SessionMessage__Revoked_Closure)
                 (const Yoke__Plugin__V1__SessionMessage__Revoked *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__SessionMessage_Closure)
                 (const Yoke__Plugin__V1__SessionMessage *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Control__Command_Closure)
                 (const Yoke__Plugin__V1__Control__Command *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Control__Activate_Closure)
                 (const Yoke__Plugin__V1__Control__Activate *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Control__Stop_Closure)
                 (const Yoke__Plugin__V1__Control__Stop *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Control_Closure)
                 (const Yoke__Plugin__V1__Control *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Ack_Closure)
                 (const Yoke__Plugin__V1__Ack *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Query__Question_Closure)
                 (const Yoke__Plugin__V1__Query__Question *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Query__Answer_Closure)
                 (const Yoke__Plugin__V1__Query__Answer *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Query_Closure)
                 (const Yoke__Plugin__V1__Query *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Data_Closure)
                 (const Yoke__Plugin__V1__Data *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Health_Closure)
                 (const Yoke__Plugin__V1__Health *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Event_Closure)
                 (const Yoke__Plugin__V1__Event *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Error__Divergence_Closure)
                 (const Yoke__Plugin__V1__Error__Divergence *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Error__Withheld_Closure)
                 (const Yoke__Plugin__V1__Error__Withheld *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Error_Closure)
                 (const Yoke__Plugin__V1__Error *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__open__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__close__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__revoked__descriptor;
extern const ProtobufCEnumDescriptor    yoke__plugin__v1__session_message__revoked__cause__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__control__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__control__command__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__control__activate__descriptor;
extern const ProtobufCEnumDescriptor    yoke__plugin__v1__control__activate__transport__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__control__stop__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__ack__descriptor;
extern const ProtobufCEnumDescriptor    yoke__plugin__v1__ack__outcome__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__query__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__query__question__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__query__answer__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__data__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__health__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__event__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__error__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__error__divergence__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__error__withheld__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2fplugin_2fv1_2ffamilies_2eproto__INCLUDED */
