/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/families.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/plugin/v1/families.pb-c.h"
void   yoke__plugin__v1__session_message__open__init
                     (Yoke__Plugin__V1__SessionMessage__Open         *message)
{
  static const Yoke__Plugin__V1__SessionMessage__Open init_value = YOKE__PLUGIN__V1__SESSION_MESSAGE__OPEN__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__session_message__close__init
                     (Yoke__Plugin__V1__SessionMessage__Close         *message)
{
  static const Yoke__Plugin__V1__SessionMessage__Close init_value = YOKE__PLUGIN__V1__SESSION_MESSAGE__CLOSE__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__session_message__revoked__init
                     (Yoke__Plugin__V1__SessionMessage__Revoked         *message)
{
  static const Yoke__Plugin__V1__SessionMessage__Revoked init_value = YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__session_message__init
                     (Yoke__Plugin__V1__SessionMessage         *message)
{
  static const Yoke__Plugin__V1__SessionMessage init_value = YOKE__PLUGIN__V1__SESSION_MESSAGE__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__session_message__get_packed_size
                     (const Yoke__Plugin__V1__SessionMessage *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__session_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__session_message__pack
                     (const Yoke__Plugin__V1__SessionMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__session_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__session_message__pack_to_buffer
                     (const Yoke__Plugin__V1__SessionMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__session_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__SessionMessage *
       yoke__plugin__v1__session_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__SessionMessage *)
     protobuf_c_message_unpack (&yoke__plugin__v1__session_message__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__session_message__free_unpacked
                     (Yoke__Plugin__V1__SessionMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__session_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__control__command__init
                     (Yoke__Plugin__V1__Control__Command         *message)
{
  static const Yoke__Plugin__V1__Control__Command init_value = YOKE__PLUGIN__V1__CONTROL__COMMAND__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__control__activate__init
                     (Yoke__Plugin__V1__Control__Activate         *message)
{
  static const Yoke__Plugin__V1__Control__Activate init_value = YOKE__PLUGIN__V1__CONTROL__ACTIVATE__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__control__stop__init
                     (Yoke__Plugin__V1__Control__Stop         *message)
{
  static const Yoke__Plugin__V1__Control__Stop init_value = YOKE__PLUGIN__V1__CONTROL__STOP__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__control__init
                     (Yoke__Plugin__V1__Control         *message)
{
  static const Yoke__Plugin__V1__Control init_value = YOKE__PLUGIN__V1__CONTROL__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__control__get_packed_size
                     (const Yoke__Plugin__V1__Control *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__control__pack
                     (const Yoke__Plugin__V1__Control *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__control__pack_to_buffer
                     (const Yoke__Plugin__V1__Control *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Control *
       yoke__plugin__v1__control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Control *)
     protobuf_c_message_unpack (&yoke__plugin__v1__control__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__control__free_unpacked
                     (Yoke__Plugin__V1__Control *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__ack__init
                     (Yoke__Plugin__V1__Ack         *message)
{
  static const Yoke__Plugin__V1__Ack init_value = YOKE__PLUGIN__V1__ACK__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__ack__get_packed_size
                     (const Yoke__Plugin__V1__Ack *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__ack__pack
                     (const Yoke__Plugin__V1__Ack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__ack__pack_to_buffer
                     (const Yoke__Plugin__V1__Ack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Ack *
       yoke__plugin__v1__ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Ack *)
     protobuf_c_message_unpack (&yoke__plugin__v1__ack__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__ack__free_unpacked
                     (Yoke__Plugin__V1__Ack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__query__question__init
                     (Yoke__Plugin__V1__Query__Question         *message)
{
  static const Yoke__Plugin__V1__Query__Question init_value = YOKE__PLUGIN__V1__QUERY__QUESTION__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__query__answer__init
                     (Yoke__Plugin__V1__Query__Answer         *message)
{
  static const Yoke__Plugin__V1__Query__Answer init_value = YOKE__PLUGIN__V1__QUERY__ANSWER__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__query__init
                     (Yoke__Plugin__V1__Query         *message)
{
  static const Yoke__Plugin__V1__Query init_value = YOKE__PLUGIN__V1__QUERY__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__query__get_packed_size
                     (const Yoke__Plugin__V1__Query *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__query__pack
                     (const Yoke__Plugin__V1__Query *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__query__pack_to_buffer
                     (const Yoke__Plugin__V1__Query *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Query *
       yoke__plugin__v1__query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Query *)
     protobuf_c_message_unpack (&yoke__plugin__v1__query__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__query__free_unpacked
                     (Yoke__Plugin__V1__Query *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__data__init
                     (Yoke__Plugin__V1__Data         *message)
{
  static const Yoke__Plugin__V1__Data init_value = YOKE__PLUGIN__V1__DATA__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__data__get_packed_size
                     (const Yoke__Plugin__V1__Data *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__data__pack
                     (const Yoke__Plugin__V1__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__data__pack_to_buffer
                     (const Yoke__Plugin__V1__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Data *
       yoke__plugin__v1__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Data *)
     protobuf_c_message_unpack (&yoke__plugin__v1__data__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__data__free_unpacked
                     (Yoke__Plugin__V1__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__health__init
                     (Yoke__Plugin__V1__Health         *message)
{
  static const Yoke__Plugin__V1__Health init_value = YOKE__PLUGIN__V1__HEALTH__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__health__get_packed_size
                     (const Yoke__Plugin__V1__Health *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__health__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__health__pack
                     (const Yoke__Plugin__V1__Health *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__health__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__health__pack_to_buffer
                     (const Yoke__Plugin__V1__Health *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__health__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Health *
       yoke__plugin__v1__health__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Health *)
     protobuf_c_message_unpack (&yoke__plugin__v1__health__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__health__free_unpacked
                     (Yoke__Plugin__V1__Health *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__health__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__event__init
                     (Yoke__Plugin__V1__Event         *message)
{
  static const Yoke__Plugin__V1__Event init_value = YOKE__PLUGIN__V1__EVENT__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__event__get_packed_size
                     (const Yoke__Plugin__V1__Event *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__event__pack
                     (const Yoke__Plugin__V1__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__event__pack_to_buffer
                     (const Yoke__Plugin__V1__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Event *
       yoke__plugin__v1__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Event *)
     protobuf_c_message_unpack (&yoke__plugin__v1__event__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__event__free_unpacked
                     (Yoke__Plugin__V1__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__error__divergence__init
                     (Yoke__Plugin__V1__Error__Divergence         *message)
{
  static const Yoke__Plugin__V1__Error__Divergence init_value = YOKE__PLUGIN__V1__ERROR__DIVERGENCE__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__error__withheld__init
                     (Yoke__Plugin__V1__Error__Withheld         *message)
{
  static const Yoke__Plugin__V1__Error__Withheld init_value = YOKE__PLUGIN__V1__ERROR__WITHHELD__INIT;
  *message = init_value;
}
void   yoke__plugin__v1__error__init
                     (Yoke__Plugin__V1__Error         *message)
{
  static const Yoke__Plugin__V1__Error init_value = YOKE__PLUGIN__V1__ERROR__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__error__get_packed_size
                     (const Yoke__Plugin__V1__Error *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__error__pack
                     (const Yoke__Plugin__V1__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__error__pack_to_buffer
                     (const Yoke__Plugin__V1__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Error *
       yoke__plugin__v1__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Error *)
     protobuf_c_message_unpack (&yoke__plugin__v1__error__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__error__free_unpacked
                     (Yoke__Plugin__V1__Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define yoke__plugin__v1__session_message__open__field_descriptors NULL
#define yoke__plugin__v1__session_message__open__field_indices_by_name NULL
#define yoke__plugin__v1__session_message__open__number_ranges NULL
const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__open__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.SessionMessage.Open",
  "Open",
  "Yoke__Plugin__V1__SessionMessage__Open",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__SessionMessage__Open),
  0,
  yoke__plugin__v1__session_message__open__field_descriptors,
  yoke__plugin__v1__session_message__open__field_indices_by_name,
  0,  yoke__plugin__v1__session_message__open__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__session_message__open__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define yoke__plugin__v1__session_message__close__field_descriptors NULL
#define yoke__plugin__v1__session_message__close__field_indices_by_name NULL
#define yoke__plugin__v1__session_message__close__number_ranges NULL
const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.SessionMessage.Close",
  "Close",
  "Yoke__Plugin__V1__SessionMessage__Close",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__SessionMessage__Close),
  0,
  yoke__plugin__v1__session_message__close__field_descriptors,
  yoke__plugin__v1__session_message__close__field_indices_by_name,
  0,  yoke__plugin__v1__session_message__close__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__session_message__close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__plugin__v1__session_message__revoked__cause__enum_values_by_number[5] =
{
  { "CAUSE_UNSPECIFIED", "YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_UNSPECIFIED", 0 },
  { "CAUSE_LIVENESS_LOST", "YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_LIVENESS_LOST", 1 },
  { "CAUSE_PLUGIN_DISABLED", "YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_PLUGIN_DISABLED", 2 },
  { "CAUSE_SCOPE_EXCEEDED", "YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_SCOPE_EXCEEDED", 3 },
  { "CAUSE_PROTOCOL_FAILURE", "YOKE__PLUGIN__V1__SESSION_MESSAGE__REVOKED__CAUSE__CAUSE_PROTOCOL_FAILURE", 4 },
};
static const ProtobufCIntRange yoke__plugin__v1__session_message__revoked__cause__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__session_message__revoked__cause__enum_values_by_name[5] =
{
  { "CAUSE_LIVENESS_LOST", 1 },
  { "CAUSE_PLUGIN_DISABLED", 2 },
  { "CAUSE_PROTOCOL_FAILURE", 4 },
  { "CAUSE_SCOPE_EXCEEDED", 3 },
  { "CAUSE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__session_message__revoked__cause__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.SessionMessage.Revoked.Cause",
  "Cause",
  "Yoke__Plugin__V1__SessionMessage__Revoked__Cause",
  "yoke.plugin.v1",
  5,
  yoke__plugin__v1__session_message__revoked__cause__enum_values_by_number,
  5,
  yoke__plugin__v1__session_message__revoked__cause__enum_values_by_name,
  1,
  yoke__plugin__v1__session_message__revoked__cause__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__session_message__revoked__field_descriptors[2] =
{
  {
    "cause",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__SessionMessage__Revoked, cause),
    &yoke__plugin__v1__session_message__revoked__cause__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__SessionMessage__Revoked, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__session_message__revoked__field_indices_by_name[] = {
  0,   /* field[0] = cause */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange yoke__plugin__v1__session_message__revoked__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__revoked__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.SessionMessage.Revoked",
  "Revoked",
  "Yoke__Plugin__V1__SessionMessage__Revoked",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__SessionMessage__Revoked),
  2,
  yoke__plugin__v1__session_message__revoked__field_descriptors,
  yoke__plugin__v1__session_message__revoked__field_indices_by_name,
  1,  yoke__plugin__v1__session_message__revoked__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__session_message__revoked__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__session_message__field_descriptors[3] =
{
  {
    "open",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__SessionMessage, kind_case),
    offsetof(Yoke__Plugin__V1__SessionMessage, open),
    &yoke__plugin__v1__session_message__open__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "close",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__SessionMessage, kind_case),
    offsetof(Yoke__Plugin__V1__SessionMessage, close),
    &yoke__plugin__v1__session_message__close__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revoked",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__SessionMessage, kind_case),
    offsetof(Yoke__Plugin__V1__SessionMessage, revoked),
    &yoke__plugin__v1__session_message__revoked__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__session_message__field_indices_by_name[] = {
  1,   /* field[1] = close */
  0,   /* field[0] = open */
  2,   /* field[2] = revoked */
};
static const ProtobufCIntRange yoke__plugin__v1__session_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__session_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.SessionMessage",
  "SessionMessage",
  "Yoke__Plugin__V1__SessionMessage",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__SessionMessage),
  3,
  yoke__plugin__v1__session_message__field_descriptors,
  yoke__plugin__v1__session_message__field_indices_by_name,
  1,  yoke__plugin__v1__session_message__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__session_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__control__command__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Command, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Command, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__control__command__field_indices_by_name[] = {
  1,   /* field[1] = payload */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange yoke__plugin__v1__control__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__control__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Control.Command",
  "Command",
  "Yoke__Plugin__V1__Control__Command",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Control__Command),
  2,
  yoke__plugin__v1__control__command__field_descriptors,
  yoke__plugin__v1__control__command__field_indices_by_name,
  1,  yoke__plugin__v1__control__command__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__control__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__plugin__v1__control__activate__transport__enum_values_by_number[4] =
{
  { "TRANSPORT_UNSPECIFIED", "YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_UNSPECIFIED", 0 },
  { "TRANSPORT_ORDERED", "YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_ORDERED", 1 },
  { "TRANSPORT_FRAMED", "YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_FRAMED", 2 },
  { "TRANSPORT_SHARED_OBJECT", "YOKE__PLUGIN__V1__CONTROL__ACTIVATE__TRANSPORT__TRANSPORT_SHARED_OBJECT", 3 },
};
static const ProtobufCIntRange yoke__plugin__v1__control__activate__transport__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__control__activate__transport__enum_values_by_name[4] =
{
  { "TRANSPORT_FRAMED", 2 },
  { "TRANSPORT_ORDERED", 1 },
  { "TRANSPORT_SHARED_OBJECT", 3 },
  { "TRANSPORT_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__control__activate__transport__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Control.Activate.Transport",
  "Transport",
  "Yoke__Plugin__V1__Control__Activate__Transport",
  "yoke.plugin.v1",
  4,
  yoke__plugin__v1__control__activate__transport__enum_values_by_number,
  4,
  yoke__plugin__v1__control__activate__transport__enum_values_by_name,
  1,
  yoke__plugin__v1__control__activate__transport__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__control__activate__field_descriptors[3] =
{
  {
    "stream",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Activate, stream),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Activate, transport),
    &yoke__plugin__v1__control__activate__transport__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Activate, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__control__activate__field_indices_by_name[] = {
  2,   /* field[2] = address */
  0,   /* field[0] = stream */
  1,   /* field[1] = transport */
};
static const ProtobufCIntRange yoke__plugin__v1__control__activate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__control__activate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Control.Activate",
  "Activate",
  "Yoke__Plugin__V1__Control__Activate",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Control__Activate),
  3,
  yoke__plugin__v1__control__activate__field_descriptors,
  yoke__plugin__v1__control__activate__field_indices_by_name,
  1,  yoke__plugin__v1__control__activate__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__control__activate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__control__stop__field_descriptors[1] =
{
  {
    "stream",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Control__Stop, stream),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__control__stop__field_indices_by_name[] = {
  0,   /* field[0] = stream */
};
static const ProtobufCIntRange yoke__plugin__v1__control__stop__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__control__stop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Control.Stop",
  "Stop",
  "Yoke__Plugin__V1__Control__Stop",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Control__Stop),
  1,
  yoke__plugin__v1__control__stop__field_descriptors,
  yoke__plugin__v1__control__stop__field_indices_by_name,
  1,  yoke__plugin__v1__control__stop__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__control__stop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__control__field_descriptors[3] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Control, kind_case),
    offsetof(Yoke__Plugin__V1__Control, command),
    &yoke__plugin__v1__control__command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Control, kind_case),
    offsetof(Yoke__Plugin__V1__Control, activate),
    &yoke__plugin__v1__control__activate__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Control, kind_case),
    offsetof(Yoke__Plugin__V1__Control, stop),
    &yoke__plugin__v1__control__stop__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__control__field_indices_by_name[] = {
  1,   /* field[1] = activate */
  0,   /* field[0] = command */
  2,   /* field[2] = stop */
};
static const ProtobufCIntRange yoke__plugin__v1__control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Control",
  "Control",
  "Yoke__Plugin__V1__Control",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Control),
  3,
  yoke__plugin__v1__control__field_descriptors,
  yoke__plugin__v1__control__field_indices_by_name,
  1,  yoke__plugin__v1__control__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__plugin__v1__ack__outcome__enum_values_by_number[4] =
{
  { "OUTCOME_UNSPECIFIED", "YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_UNSPECIFIED", 0 },
  { "OUTCOME_ACCEPTED", "YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_DONE", "YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_DONE", 2 },
  { "OUTCOME_FAILED", "YOKE__PLUGIN__V1__ACK__OUTCOME__OUTCOME_FAILED", 3 },
};
static const ProtobufCIntRange yoke__plugin__v1__ack__outcome__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__ack__outcome__enum_values_by_name[4] =
{
  { "OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_DONE", 2 },
  { "OUTCOME_FAILED", 3 },
  { "OUTCOME_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__ack__outcome__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Ack.Outcome",
  "Outcome",
  "Yoke__Plugin__V1__Ack__Outcome",
  "yoke.plugin.v1",
  4,
  yoke__plugin__v1__ack__outcome__enum_values_by_number,
  4,
  yoke__plugin__v1__ack__outcome__enum_values_by_name,
  1,
  yoke__plugin__v1__ack__outcome__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__ack__field_descriptors[2] =
{
  {
    "outcome",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Ack, outcome),
    &yoke__plugin__v1__ack__outcome__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Ack, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__ack__field_indices_by_name[] = {
  1,   /* field[1] = line */
  0,   /* field[0] = outcome */
};
static const ProtobufCIntRange yoke__plugin__v1__ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Ack",
  "Ack",
  "Yoke__Plugin__V1__Ack",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Ack),
  2,
  yoke__plugin__v1__ack__field_descriptors,
  yoke__plugin__v1__ack__field_indices_by_name,
  1,  yoke__plugin__v1__ack__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__query__question__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Query__Question, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Query__Question, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__query__question__field_indices_by_name[] = {
  1,   /* field[1] = payload */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange yoke__plugin__v1__query__question__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__query__question__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Query.Question",
  "Question",
  "Yoke__Plugin__V1__Query__Question",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Query__Question),
  2,
  yoke__plugin__v1__query__question__field_descriptors,
  yoke__plugin__v1__query__question__field_indices_by_name,
  1,  yoke__plugin__v1__query__question__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__query__question__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__query__answer__field_descriptors[1] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Query__Answer, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__query__answer__field_indices_by_name[] = {
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange yoke__plugin__v1__query__answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__query__answer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Query.Answer",
  "Answer",
  "Yoke__Plugin__V1__Query__Answer",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Query__Answer),
  1,
  yoke__plugin__v1__query__answer__field_descriptors,
  yoke__plugin__v1__query__answer__field_indices_by_name,
  1,  yoke__plugin__v1__query__answer__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__query__answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__query__field_descriptors[2] =
{
  {
    "question",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Query, kind_case),
    offsetof(Yoke__Plugin__V1__Query, question),
    &yoke__plugin__v1__query__question__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "answer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Query, kind_case),
    offsetof(Yoke__Plugin__V1__Query, answer),
    &yoke__plugin__v1__query__answer__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__query__field_indices_by_name[] = {
  1,   /* field[1] = answer */
  0,   /* field[0] = question */
};
static const ProtobufCIntRange yoke__plugin__v1__query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Query",
  "Query",
  "Yoke__Plugin__V1__Query",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Query),
  2,
  yoke__plugin__v1__query__field_descriptors,
  yoke__plugin__v1__query__field_indices_by_name,
  1,  yoke__plugin__v1__query__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__data__field_descriptors[2] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Data, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Data, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__data__field_indices_by_name[] = {
  1,   /* field[1] = payload */
  0,   /* field[0] = sequence */
};
static const ProtobufCIntRange yoke__plugin__v1__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Data",
  "Data",
  "Yoke__Plugin__V1__Data",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Data),
  2,
  yoke__plugin__v1__data__field_descriptors,
  yoke__plugin__v1__data__field_indices_by_name,
  1,  yoke__plugin__v1__data__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__health__field_descriptors[2] =
{
  {
    "grade",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Health, grade),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Health, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__health__field_indices_by_name[] = {
  0,   /* field[0] = grade */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange yoke__plugin__v1__health__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__health__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Health",
  "Health",
  "Yoke__Plugin__V1__Health",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Health),
  2,
  yoke__plugin__v1__health__field_descriptors,
  yoke__plugin__v1__health__field_indices_by_name,
  1,  yoke__plugin__v1__health__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__health__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__event__field_descriptors[4] =
{
  {
    "occurrence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Event, occurrence),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Event, severity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Event, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detail",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Event, detail),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__event__field_indices_by_name[] = {
  3,   /* field[3] = detail */
  2,   /* field[2] = line */
  0,   /* field[0] = occurrence */
  1,   /* field[1] = severity */
};
static const ProtobufCIntRange yoke__plugin__v1__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Event",
  "Event",
  "Yoke__Plugin__V1__Event",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Event),
  4,
  yoke__plugin__v1__event__field_descriptors,
  yoke__plugin__v1__event__field_indices_by_name,
  1,  yoke__plugin__v1__event__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__error__divergence__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Error__Divergence, n_items),
    offsetof(Yoke__Plugin__V1__Error__Divergence, items),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__error__divergence__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange yoke__plugin__v1__error__divergence__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__error__divergence__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Error.Divergence",
  "Divergence",
  "Yoke__Plugin__V1__Error__Divergence",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Error__Divergence),
  1,
  yoke__plugin__v1__error__divergence__field_descriptors,
  yoke__plugin__v1__error__divergence__field_indices_by_name,
  1,  yoke__plugin__v1__error__divergence__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__error__divergence__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__error__withheld__field_descriptors[1] =
{
  {
    "item",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Error__Withheld, item),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__error__withheld__field_indices_by_name[] = {
  0,   /* field[0] = item */
};
static const ProtobufCIntRange yoke__plugin__v1__error__withheld__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__error__withheld__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Error.Withheld",
  "Withheld",
  "Yoke__Plugin__V1__Error__Withheld",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Error__Withheld),
  1,
  yoke__plugin__v1__error__withheld__field_descriptors,
  yoke__plugin__v1__error__withheld__field_indices_by_name,
  1,  yoke__plugin__v1__error__withheld__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__error__withheld__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__error__field_descriptors[4] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Error, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Error, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "divergent",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Error, detail_case),
    offsetof(Yoke__Plugin__V1__Error, divergent),
    &yoke__plugin__v1__error__divergence__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "withheld",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Error, detail_case),
    offsetof(Yoke__Plugin__V1__Error, withheld),
    &yoke__plugin__v1__error__withheld__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__error__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = divergent */
  1,   /* field[1] = message */
  3,   /* field[3] = withheld */
};
static const ProtobufCIntRange yoke__plugin__v1__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Error",
  "Error",
  "Yoke__Plugin__V1__Error",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Error),
  4,
  yoke__plugin__v1__error__field_descriptors,
  yoke__plugin__v1__error__field_indices_by_name,
  1,  yoke__plugin__v1__error__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
