/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/register.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/plugin/v1/register.pb-c.h"
void   yoke__plugin__v1__register_request__init
                     (Yoke__Plugin__V1__RegisterRequest         *message)
{
  static const Yoke__Plugin__V1__RegisterRequest init_value = YOKE__PLUGIN__V1__REGISTER_REQUEST__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__register_request__get_packed_size
                     (const Yoke__Plugin__V1__RegisterRequest *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__register_request__pack
                     (const Yoke__Plugin__V1__RegisterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__register_request__pack_to_buffer
                     (const Yoke__Plugin__V1__RegisterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__RegisterRequest *
       yoke__plugin__v1__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__RegisterRequest *)
     protobuf_c_message_unpack (&yoke__plugin__v1__register_request__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__register_request__free_unpacked
                     (Yoke__Plugin__V1__RegisterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__register_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__surface__init
                     (Yoke__Plugin__V1__Surface         *message)
{
  static const Yoke__Plugin__V1__Surface init_value = YOKE__PLUGIN__V1__SURFACE__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__surface__get_packed_size
                     (const Yoke__Plugin__V1__Surface *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__surface__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__surface__pack
                     (const Yoke__Plugin__V1__Surface *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__surface__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__surface__pack_to_buffer
                     (const Yoke__Plugin__V1__Surface *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__surface__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Surface *
       yoke__plugin__v1__surface__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Surface *)
     protobuf_c_message_unpack (&yoke__plugin__v1__surface__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__surface__free_unpacked
                     (Yoke__Plugin__V1__Surface *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__surface__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__register_response__init
                     (Yoke__Plugin__V1__RegisterResponse         *message)
{
  static const Yoke__Plugin__V1__RegisterResponse init_value = YOKE__PLUGIN__V1__REGISTER_RESPONSE__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__register_response__get_packed_size
                     (const Yoke__Plugin__V1__RegisterResponse *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__register_response__pack
                     (const Yoke__Plugin__V1__RegisterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__register_response__pack_to_buffer
                     (const Yoke__Plugin__V1__RegisterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__register_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__RegisterResponse *
       yoke__plugin__v1__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__RegisterResponse *)
     protobuf_c_message_unpack (&yoke__plugin__v1__register_response__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__register_response__free_unpacked
                     (Yoke__Plugin__V1__RegisterResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__register_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__plugin__v1__heartbeat_terms__init
                     (Yoke__Plugin__V1__HeartbeatTerms         *message)
{
  static const Yoke__Plugin__V1__HeartbeatTerms init_value = YOKE__PLUGIN__V1__HEARTBEAT_TERMS__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__heartbeat_terms__get_packed_size
                     (const Yoke__Plugin__V1__HeartbeatTerms *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__heartbeat_terms__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__heartbeat_terms__pack
                     (const Yoke__Plugin__V1__HeartbeatTerms *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__heartbeat_terms__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__heartbeat_terms__pack_to_buffer
                     (const Yoke__Plugin__V1__HeartbeatTerms *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__heartbeat_terms__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__HeartbeatTerms *
       yoke__plugin__v1__heartbeat_terms__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__HeartbeatTerms *)
     protobuf_c_message_unpack (&yoke__plugin__v1__heartbeat_terms__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__heartbeat_terms__free_unpacked
                     (Yoke__Plugin__V1__HeartbeatTerms *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__heartbeat_terms__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__plugin__v1__register_request__field_descriptors[8] =
{
  {
    "plugin",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, plugin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, unit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "artifact_version",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, artifact_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, language),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdk_line",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, sdk_line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "declared",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterRequest, declared),
    &yoke__plugin__v1__surface__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__register_request__field_indices_by_name[] = {
  4,   /* field[4] = artifact_version */
  7,   /* field[7] = declared */
  5,   /* field[5] = language */
  0,   /* field[0] = plugin */
  3,   /* field[3] = protocol */
  6,   /* field[6] = sdk_line */
  2,   /* field[2] = token */
  1,   /* field[1] = unit */
};
static const ProtobufCIntRange yoke__plugin__v1__register_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__register_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.RegisterRequest",
  "RegisterRequest",
  "Yoke__Plugin__V1__RegisterRequest",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__RegisterRequest),
  8,
  yoke__plugin__v1__register_request__field_descriptors,
  yoke__plugin__v1__register_request__field_indices_by_name,
  1,  yoke__plugin__v1__register_request__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__register_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__surface__field_descriptors[5] =
{
  {
    "capabilities",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Surface, n_capabilities),
    offsetof(Yoke__Plugin__V1__Surface, capabilities),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streams",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Surface, n_streams),
    offsetof(Yoke__Plugin__V1__Surface, streams),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commands",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Surface, n_commands),
    offsetof(Yoke__Plugin__V1__Surface, commands),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queries",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Surface, n_queries),
    offsetof(Yoke__Plugin__V1__Surface, queries),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occurrences",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Plugin__V1__Surface, n_occurrences),
    offsetof(Yoke__Plugin__V1__Surface, occurrences),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__surface__field_indices_by_name[] = {
  0,   /* field[0] = capabilities */
  2,   /* field[2] = commands */
  4,   /* field[4] = occurrences */
  3,   /* field[3] = queries */
  1,   /* field[1] = streams */
};
static const ProtobufCIntRange yoke__plugin__v1__surface__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__surface__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Surface",
  "Surface",
  "Yoke__Plugin__V1__Surface",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Surface),
  5,
  yoke__plugin__v1__surface__field_descriptors,
  yoke__plugin__v1__surface__field_indices_by_name,
  1,  yoke__plugin__v1__surface__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__surface__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__plugin__v1__register_response__outcome__enum_values_by_number[4] =
{
  { "OUTCOME_UNSPECIFIED", "YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_UNSPECIFIED", 0 },
  { "OUTCOME_ACCEPTED", "YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_ACCEPTED_WITH_RESTRICTIONS", "YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_ACCEPTED_WITH_RESTRICTIONS", 2 },
  { "OUTCOME_REFUSED", "YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_REFUSED", 3 },
};
static const ProtobufCIntRange yoke__plugin__v1__register_response__outcome__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__register_response__outcome__enum_values_by_name[4] =
{
  { "OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_ACCEPTED_WITH_RESTRICTIONS", 2 },
  { "OUTCOME_REFUSED", 3 },
  { "OUTCOME_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__register_response__outcome__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.RegisterResponse.Outcome",
  "Outcome",
  "Yoke__Plugin__V1__RegisterResponse__Outcome",
  "yoke.plugin.v1",
  4,
  yoke__plugin__v1__register_response__outcome__enum_values_by_number,
  4,
  yoke__plugin__v1__register_response__outcome__enum_values_by_name,
  1,
  yoke__plugin__v1__register_response__outcome__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__register_response__field_descriptors[8] =
{
  {
    "outcome",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, outcome),
    &yoke__plugin__v1__register_response__outcome__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, stage),
    &yoke__plugin__v1__stage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, session_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "granted",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, granted),
    &yoke__plugin__v1__surface__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "withheld",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, withheld),
    &yoke__plugin__v1__surface__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__RegisterResponse, heartbeat),
    &yoke__plugin__v1__heartbeat_terms__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__register_response__field_indices_by_name[] = {
  2,   /* field[2] = code */
  5,   /* field[5] = granted */
  7,   /* field[7] = heartbeat */
  3,   /* field[3] = message */
  0,   /* field[0] = outcome */
  4,   /* field[4] = session_id */
  1,   /* field[1] = stage */
  6,   /* field[6] = withheld */
};
static const ProtobufCIntRange yoke__plugin__v1__register_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__register_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.RegisterResponse",
  "RegisterResponse",
  "Yoke__Plugin__V1__RegisterResponse",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__RegisterResponse),
  8,
  yoke__plugin__v1__register_response__field_descriptors,
  yoke__plugin__v1__register_response__field_indices_by_name,
  1,  yoke__plugin__v1__register_response__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__register_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__plugin__v1__heartbeat_terms__field_descriptors[2] =
{
  {
    "interval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__HeartbeatTerms, interval),
    &google__protobuf__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tolerance",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__HeartbeatTerms, tolerance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__heartbeat_terms__field_indices_by_name[] = {
  0,   /* field[0] = interval */
  1,   /* field[1] = tolerance */
};
static const ProtobufCIntRange yoke__plugin__v1__heartbeat_terms__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__heartbeat_terms__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.HeartbeatTerms",
  "HeartbeatTerms",
  "Yoke__Plugin__V1__HeartbeatTerms",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__HeartbeatTerms),
  2,
  yoke__plugin__v1__heartbeat_terms__field_descriptors,
  yoke__plugin__v1__heartbeat_terms__field_indices_by_name,
  1,  yoke__plugin__v1__heartbeat_terms__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__heartbeat_terms__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__plugin__v1__stage__enum_values_by_number[10] =
{
  { "STAGE_UNSPECIFIED", "YOKE__PLUGIN__V1__STAGE__STAGE_UNSPECIFIED", 0 },
  { "STAGE_STRUCTURAL", "YOKE__PLUGIN__V1__STAGE__STAGE_STRUCTURAL", 1 },
  { "STAGE_IDENTITY", "YOKE__PLUGIN__V1__STAGE__STAGE_IDENTITY", 2 },
  { "STAGE_ADMINISTRATIVE_STATE", "YOKE__PLUGIN__V1__STAGE__STAGE_ADMINISTRATIVE_STATE", 3 },
  { "STAGE_AUTHENTICATION", "YOKE__PLUGIN__V1__STAGE__STAGE_AUTHENTICATION", 4 },
  { "STAGE_COMPATIBILITY", "YOKE__PLUGIN__V1__STAGE__STAGE_COMPATIBILITY", 5 },
  { "STAGE_DECLARATION_CONSISTENCY", "YOKE__PLUGIN__V1__STAGE__STAGE_DECLARATION_CONSISTENCY", 6 },
  { "STAGE_AUTHORISATION", "YOKE__PLUGIN__V1__STAGE__STAGE_AUTHORISATION", 7 },
  { "STAGE_UNIT_CONFLICT", "YOKE__PLUGIN__V1__STAGE__STAGE_UNIT_CONFLICT", 8 },
  { "STAGE_SESSION_PREPARATION", "YOKE__PLUGIN__V1__STAGE__STAGE_SESSION_PREPARATION", 9 },
};
static const ProtobufCIntRange yoke__plugin__v1__stage__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex yoke__plugin__v1__stage__enum_values_by_name[10] =
{
  { "STAGE_ADMINISTRATIVE_STATE", 3 },
  { "STAGE_AUTHENTICATION", 4 },
  { "STAGE_AUTHORISATION", 7 },
  { "STAGE_COMPATIBILITY", 5 },
  { "STAGE_DECLARATION_CONSISTENCY", 6 },
  { "STAGE_IDENTITY", 2 },
  { "STAGE_SESSION_PREPARATION", 9 },
  { "STAGE_STRUCTURAL", 1 },
  { "STAGE_UNIT_CONFLICT", 8 },
  { "STAGE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__plugin__v1__stage__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Stage",
  "Stage",
  "Yoke__Plugin__V1__Stage",
  "yoke.plugin.v1",
  10,
  yoke__plugin__v1__stage__enum_values_by_number,
  10,
  yoke__plugin__v1__stage__enum_values_by_name,
  1,
  yoke__plugin__v1__stage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
