/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/register.proto */

#ifndef PROTOBUF_C_yoke_2fplugin_2fv1_2fregister_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2fplugin_2fv1_2fregister_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/duration.pb-c.h"

typedef struct Yoke__Plugin__V1__RegisterRequest Yoke__Plugin__V1__RegisterRequest;
typedef struct Yoke__Plugin__V1__Surface Yoke__Plugin__V1__Surface;
typedef struct Yoke__Plugin__V1__RegisterResponse Yoke__Plugin__V1__RegisterResponse;
typedef struct Yoke__Plugin__V1__HeartbeatTerms Yoke__Plugin__V1__HeartbeatTerms;


/* --- enums --- */

typedef enum _Yoke__Plugin__V1__RegisterResponse__Outcome {
  YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_UNSPECIFIED = 0,
  YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_ACCEPTED = 1,
  YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_ACCEPTED_WITH_RESTRICTIONS = 2,
  YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_REFUSED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME)
} Yoke__Plugin__V1__RegisterResponse__Outcome;
/*
 * The nine stages of admission, in the order they are evaluated.
 */
typedef enum _Yoke__Plugin__V1__Stage {
  YOKE__PLUGIN__V1__STAGE__STAGE_UNSPECIFIED = 0,
  YOKE__PLUGIN__V1__STAGE__STAGE_STRUCTURAL = 1,
  YOKE__PLUGIN__V1__STAGE__STAGE_IDENTITY = 2,
  YOKE__PLUGIN__V1__STAGE__STAGE_ADMINISTRATIVE_STATE = 3,
  YOKE__PLUGIN__V1__STAGE__STAGE_AUTHENTICATION = 4,
  YOKE__PLUGIN__V1__STAGE__STAGE_COMPATIBILITY = 5,
  YOKE__PLUGIN__V1__STAGE__STAGE_DECLARATION_CONSISTENCY = 6,
  YOKE__PLUGIN__V1__STAGE__STAGE_AUTHORISATION = 7,
  YOKE__PLUGIN__V1__STAGE__STAGE_UNIT_CONFLICT = 8,
  YOKE__PLUGIN__V1__STAGE__STAGE_SESSION_PREPARATION = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__STAGE)
} Yoke__Plugin__V1__Stage;

/* --- messages --- */

/*
 * What a unit claims. No address, no Session identity and no state.
 */
struct  Yoke__Plugin__V1__RegisterRequest
{
  ProtobufCMessage base;
  /*
   * The plugin and unit identities, exactly as the environment supplied them.
   */
  char *plugin;
  char *unit;
  /*
   * The bootstrap token: opaque, never logged and never stored.
   */
  char *token;
  /*
   * The protocol version: the Contract this unit was built against.
   */
  uint32_t protocol;
  /*
   * Recorded and reported, and never weighed.
   */
  char *artifact_version;
  char *language;
  char *sdk_line;
  /*
   * The declared surface.
   */
  Yoke__Plugin__V1__Surface *declared;
};
#define YOKE__PLUGIN__V1__REGISTER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__register_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL }


/*
 * Five lists of identifiers: a declared surface, a granted scope, or what was withheld from one.
 */
struct  Yoke__Plugin__V1__Surface
{
  ProtobufCMessage base;
  size_t n_capabilities;
  char **capabilities;
  size_t n_streams;
  char **streams;
  size_t n_commands;
  char **commands;
  size_t n_queries;
  char **queries;
  size_t n_occurrences;
  char **occurrences;
};
#define YOKE__PLUGIN__V1__SURFACE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__surface__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  Yoke__Plugin__V1__RegisterResponse
{
  ProtobufCMessage base;
  Yoke__Plugin__V1__RegisterResponse__Outcome outcome;
  /*
   * On a refusal: how far the request got, which decides whether the token was spent.
   */
  Yoke__Plugin__V1__Stage stage;
  /*
   * On a refusal: the machine's answer, one of Code's names, and the person's.
   */
  char *code;
  char *message;
  /*
   * On an acceptance: opaque, assigned by the Core, and not guessable.
   */
  char *session_id;
  /*
   * On an acceptance: the four lists after the intersection.
   */
  Yoke__Plugin__V1__Surface *granted;
  /*
   * On a restricted acceptance: item by item, never a count.
   */
  Yoke__Plugin__V1__Surface *withheld;
  /*
   * The terms the Core assigned.
   */
  Yoke__Plugin__V1__HeartbeatTerms *heartbeat;
};
#define YOKE__PLUGIN__V1__REGISTER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__register_response__descriptor) \
    , YOKE__PLUGIN__V1__REGISTER_RESPONSE__OUTCOME__OUTCOME_UNSPECIFIED, YOKE__PLUGIN__V1__STAGE__STAGE_UNSPECIFIED, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, NULL, NULL }


struct  Yoke__Plugin__V1__HeartbeatTerms
{
  ProtobufCMessage base;
  Google__Protobuf__Duration *interval;
  /*
   * How many consecutive misses the Core tolerates.
   */
  uint32_t tolerance;
};
#define YOKE__PLUGIN__V1__HEARTBEAT_TERMS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__heartbeat_terms__descriptor) \
    , NULL, 0 }


/* Yoke__Plugin__V1__RegisterRequest methods */
void   yoke__plugin__v1__register_request__init
                     (Yoke__Plugin__V1__RegisterRequest         *message);
size_t yoke__plugin__v1__register_request__get_packed_size
                     (const Yoke__Plugin__V1__RegisterRequest   *message);
size_t yoke__plugin__v1__register_request__pack
                     (const Yoke__Plugin__V1__RegisterRequest   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__register_request__pack_to_buffer
                     (const Yoke__Plugin__V1__RegisterRequest   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__RegisterRequest *
       yoke__plugin__v1__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__register_request__free_unpacked
                     (Yoke__Plugin__V1__RegisterRequest *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__Surface methods */
void   yoke__plugin__v1__surface__init
                     (Yoke__Plugin__V1__Surface         *message);
size_t yoke__plugin__v1__surface__get_packed_size
                     (const Yoke__Plugin__V1__Surface   *message);
size_t yoke__plugin__v1__surface__pack
                     (const Yoke__Plugin__V1__Surface   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__surface__pack_to_buffer
                     (const Yoke__Plugin__V1__Surface   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Surface *
       yoke__plugin__v1__surface__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__surface__free_unpacked
                     (Yoke__Plugin__V1__Surface *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__RegisterResponse methods */
void   yoke__plugin__v1__register_response__init
                     (Yoke__Plugin__V1__RegisterResponse         *message);
size_t yoke__plugin__v1__register_response__get_packed_size
                     (const Yoke__Plugin__V1__RegisterResponse   *message);
size_t yoke__plugin__v1__register_response__pack
                     (const Yoke__Plugin__V1__RegisterResponse   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__register_response__pack_to_buffer
                     (const Yoke__Plugin__V1__RegisterResponse   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__RegisterResponse *
       yoke__plugin__v1__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__register_response__free_unpacked
                     (Yoke__Plugin__V1__RegisterResponse *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Plugin__V1__HeartbeatTerms methods */
void   yoke__plugin__v1__heartbeat_terms__init
                     (Yoke__Plugin__V1__HeartbeatTerms         *message);
size_t yoke__plugin__v1__heartbeat_terms__get_packed_size
                     (const Yoke__Plugin__V1__HeartbeatTerms   *message);
size_t yoke__plugin__v1__heartbeat_terms__pack
                     (const Yoke__Plugin__V1__HeartbeatTerms   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__heartbeat_terms__pack_to_buffer
                     (const Yoke__Plugin__V1__HeartbeatTerms   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__HeartbeatTerms *
       yoke__plugin__v1__heartbeat_terms__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__heartbeat_terms__free_unpacked
                     (Yoke__Plugin__V1__HeartbeatTerms *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Plugin__V1__RegisterRequest_Closure)
                 (const Yoke__Plugin__V1__RegisterRequest *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__Surface_Closure)
                 (const Yoke__Plugin__V1__Surface *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__RegisterResponse_Closure)
                 (const Yoke__Plugin__V1__RegisterResponse *message,
                  void *closure_data);
typedef void (*Yoke__Plugin__V1__HeartbeatTerms_Closure)
                 (const Yoke__Plugin__V1__HeartbeatTerms *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    yoke__plugin__v1__stage__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__register_request__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__surface__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__register_response__descriptor;
extern const ProtobufCEnumDescriptor    yoke__plugin__v1__register_response__outcome__descriptor;
extern const ProtobufCMessageDescriptor yoke__plugin__v1__heartbeat_terms__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2fplugin_2fv1_2fregister_2eproto__INCLUDED */
