/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/session.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/plugin/v1/session.pb-c.h"
void   yoke__plugin__v1__envelope__init
                     (Yoke__Plugin__V1__Envelope         *message)
{
  static const Yoke__Plugin__V1__Envelope init_value = YOKE__PLUGIN__V1__ENVELOPE__INIT;
  *message = init_value;
}
size_t yoke__plugin__v1__envelope__get_packed_size
                     (const Yoke__Plugin__V1__Envelope *message)
{
  assert(message->base.descriptor == &yoke__plugin__v1__envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__plugin__v1__envelope__pack
                     (const Yoke__Plugin__V1__Envelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__plugin__v1__envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__plugin__v1__envelope__pack_to_buffer
                     (const Yoke__Plugin__V1__Envelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__plugin__v1__envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Plugin__V1__Envelope *
       yoke__plugin__v1__envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Plugin__V1__Envelope *)
     protobuf_c_message_unpack (&yoke__plugin__v1__envelope__descriptor,
                                allocator, len, data);
}
void   yoke__plugin__v1__envelope__free_unpacked
                     (Yoke__Plugin__V1__Envelope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__plugin__v1__envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__plugin__v1__envelope__field_descriptors[12] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Envelope, message_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Envelope, session_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sent_at_unix_nano",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Envelope, sent_at_unix_nano),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "correlation_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Plugin__V1__Envelope, correlation_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, session),
    &yoke__plugin__v1__session_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, control),
    &yoke__plugin__v1__control__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, ack),
    &yoke__plugin__v1__ack__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, query),
    &yoke__plugin__v1__query__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, data),
    &yoke__plugin__v1__data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, health),
    &yoke__plugin__v1__health__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, event),
    &yoke__plugin__v1__event__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Plugin__V1__Envelope, payload_case),
    offsetof(Yoke__Plugin__V1__Envelope, error),
    &yoke__plugin__v1__error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__plugin__v1__envelope__field_indices_by_name[] = {
  6,   /* field[6] = ack */
  5,   /* field[5] = control */
  3,   /* field[3] = correlation_id */
  8,   /* field[8] = data */
  11,   /* field[11] = error */
  10,   /* field[10] = event */
  9,   /* field[9] = health */
  0,   /* field[0] = message_id */
  7,   /* field[7] = query */
  2,   /* field[2] = sent_at_unix_nano */
  4,   /* field[4] = session */
  1,   /* field[1] = session_id */
};
static const ProtobufCIntRange yoke__plugin__v1__envelope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor yoke__plugin__v1__envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.plugin.v1.Envelope",
  "Envelope",
  "Yoke__Plugin__V1__Envelope",
  "yoke.plugin.v1",
  sizeof(Yoke__Plugin__V1__Envelope),
  12,
  yoke__plugin__v1__envelope__field_descriptors,
  yoke__plugin__v1__envelope__field_indices_by_name,
  1,  yoke__plugin__v1__envelope__number_ranges,
  (ProtobufCMessageInit) yoke__plugin__v1__envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
