/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/plugin/v1/session.proto */

#ifndef PROTOBUF_C_yoke_2fplugin_2fv1_2fsession_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2fplugin_2fv1_2fsession_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "yoke/plugin/v1/families.pb-c.h"

typedef struct Yoke__Plugin__V1__Envelope Yoke__Plugin__V1__Envelope;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD__NOT_SET = 0,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_SESSION = 5,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_CONTROL = 6,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_ACK = 7,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_QUERY = 8,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_DATA = 9,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_HEALTH = 10,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_EVENT = 11,
  YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD_ERROR = 12
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD__CASE)
} Yoke__Plugin__V1__Envelope__PayloadCase;

/*
 * Four header fields and exactly one payload. The payload that is set is the family.
 */
struct  Yoke__Plugin__V1__Envelope
{
  ProtobufCMessage base;
  /*
   * Unique within the Session.
   */
  char *message_id;
  /*
   * The identity admission issued.
   */
  char *session_id;
  /*
   * The sender's clock at emission, in nanoseconds since the epoch.
   */
  int64_t sent_at_unix_nano;
  /*
   * The message identity of what this answers; empty where the family never correlates.
   */
  char *correlation_id;
  Yoke__Plugin__V1__Envelope__PayloadCase payload_case;
  union {
    Yoke__Plugin__V1__SessionMessage *session;
    Yoke__Plugin__V1__Control *control;
    Yoke__Plugin__V1__Ack *ack;
    Yoke__Plugin__V1__Query *query;
    Yoke__Plugin__V1__Data *data;
    Yoke__Plugin__V1__Health *health;
    Yoke__Plugin__V1__Event *event;
    Yoke__Plugin__V1__Error *error;
  };
};
#define YOKE__PLUGIN__V1__ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__plugin__v1__envelope__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, YOKE__PLUGIN__V1__ENVELOPE__PAYLOAD__NOT_SET, {0} }


/* Yoke__Plugin__V1__Envelope methods */
void   yoke__plugin__v1__envelope__init
                     (Yoke__Plugin__V1__Envelope         *message);
size_t yoke__plugin__v1__envelope__get_packed_size
                     (const Yoke__Plugin__V1__Envelope   *message);
size_t yoke__plugin__v1__envelope__pack
                     (const Yoke__Plugin__V1__Envelope   *message,
                      uint8_t             *out);
size_t yoke__plugin__v1__envelope__pack_to_buffer
                     (const Yoke__Plugin__V1__Envelope   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Plugin__V1__Envelope *
       yoke__plugin__v1__envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__plugin__v1__envelope__free_unpacked
                     (Yoke__Plugin__V1__Envelope *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Plugin__V1__Envelope_Closure)
                 (const Yoke__Plugin__V1__Envelope *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__plugin__v1__envelope__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2fplugin_2fv1_2fsession_2eproto__INCLUDED */
