/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/codes.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2fcodes_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2fcodes_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/descriptor.pb-c.h"

typedef struct Yoke__Interface__V1__Refusal Yoke__Interface__V1__Refusal;
typedef struct Yoke__Interface__V1__Subject Yoke__Interface__V1__Subject;
typedef struct Yoke__Interface__V1__Suspension Yoke__Interface__V1__Suspension;


/* --- enums --- */

typedef enum _Yoke__Interface__V1__Code {
  YOKE__INTERFACE__V1__CODE__CODE_UNSPECIFIED = 0,
  /*
   * The request does not decode, or a required field is absent.
   */
  YOKE__INTERFACE__V1__CODE__CODE_OPERATION_MALFORMED = 1,
  /*
   * It names an operation this Core does not implement.
   */
  YOKE__INTERFACE__V1__CODE__CODE_OPERATION_UNKNOWN = 2,
  /*
   * The contract version is absent, or this Core does not support it.
   */
  YOKE__INTERFACE__V1__CODE__CODE_COMPAT_UNSUPPORTED = 3,
  /*
   * The channel's class requires a credential and none was presented.
   */
  YOKE__INTERFACE__V1__CODE__CODE_AUTH_REQUIRED = 4,
  /*
   * The credential was not accepted.
   */
  YOKE__INTERFACE__V1__CODE__CODE_AUTH_INVALID = 5,
  /*
   * A single channel is already held; the first client is untouched.
   */
  YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_IN_USE = 6,
  /*
   * A control request arrived with no live attachment: the browser projection only.
   */
  YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_NOT_ATTACHED = 7,
  /*
   * The operation is withdrawn by this channel's grade.
   */
  YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_SUSPENDED = 8,
  /*
   * A reclaim on a channel not bound as a local socket.
   */
  YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_NOT_LOCAL = 9,
  /*
   * Nothing this channel may address bears that identity.
   */
  YOKE__INTERFACE__V1__CODE__CODE_SUBJECT_UNKNOWN = 10,
  /*
   * The object was never declared by the unit's Plugin.
   */
  YOKE__INTERFACE__V1__CODE__CODE_SCOPE_UNDECLARED = 11,
  /*
   * It is declared and not granted to that plugin.
   */
  YOKE__INTERFACE__V1__CODE__CODE_SCOPE_WITHHELD = 12,
  /*
   * The operation needs a running unit and this one is not.
   */
  YOKE__INTERFACE__V1__CODE__CODE_UNIT_NOT_RUNNING = 13,
  /*
   * The unit holds no Session, so nothing can be issued on one.
   */
  YOKE__INTERFACE__V1__CODE__CODE_UNIT_NO_SESSION = 14,
  /*
   * The wait elapsed with no acknowledgement or answer.
   */
  YOKE__INTERFACE__V1__CODE__CODE_UNIT_UNANSWERED = 15,
  /*
   * An orderly stop is in progress and the operation would act.
   */
  YOKE__INTERFACE__V1__CODE__CODE_INSTANCE_STOPPING = 16,
  /*
   * The unit answered the Core's message with an error; the detail carries the unit's own code.
   */
  YOKE__INTERFACE__V1__CODE__CODE_UNIT_FAILED = 17
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__CODE)
} Yoke__Interface__V1__Code;

/* --- messages --- */

typedef enum {
  YOKE__INTERFACE__V1__REFUSAL__DETAIL__NOT_SET = 0,
  YOKE__INTERFACE__V1__REFUSAL__DETAIL_SUBJECT = 3,
  YOKE__INTERFACE__V1__REFUSAL__DETAIL_ITEM = 4,
  YOKE__INTERFACE__V1__REFUSAL__DETAIL_SUSPENSION = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__REFUSAL__DETAIL__CASE)
} Yoke__Interface__V1__Refusal__DetailCase;

/*
 * A refusal: a code, a message for a person, and what it names in a detail typed per code.
 */
struct  Yoke__Interface__V1__Refusal
{
  ProtobufCMessage base;
  /*
   * One of Code's names.
   */
  char *code;
  char *message;
  Yoke__Interface__V1__Refusal__DetailCase detail_case;
  union {
    /*
     * The subject named: for subject.unknown, and for the refusals about a unit.
     */
    Yoke__Interface__V1__Subject *subject;
    /*
     * The object withheld or undeclared — a stream, a command type or a query type — or, for
     * unit.failed, the unit's own code.
     */
    char *item;
    /*
     * For channel.suspended: the grade, and the channel that prevails.
     */
    Yoke__Interface__V1__Suspension *suspension;
  };
};
#define YOKE__INTERFACE__V1__REFUSAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__refusal__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, YOKE__INTERFACE__V1__REFUSAL__DETAIL__NOT_SET, {0} }


/*
 * What an operation, a record or an event is about: a kind and an identity, and a unit's life where
 * one is named.
 */
struct  Yoke__Interface__V1__Subject
{
  ProtobufCMessage base;
  /*
   * instance, unit or channel.
   */
  char *kind;
  char *identity;
  /*
   * A unit's life; zero where none is named.
   */
  uint64_t incarnation;
};
#define YOKE__INTERFACE__V1__SUBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__subject__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * Why an operation was withdrawn: the suspended channel's grade, and the channel that prevails.
 */
struct  Yoke__Interface__V1__Suspension
{
  ProtobufCMessage base;
  /*
   * read-only or dark.
   */
  char *grade;
  /*
   * The channel that prevails; empty where none is holding.
   */
  char *by;
};
#define YOKE__INTERFACE__V1__SUSPENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__suspension__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Yoke__Interface__V1__Refusal methods */
void   yoke__interface__v1__refusal__init
                     (Yoke__Interface__V1__Refusal         *message);
size_t yoke__interface__v1__refusal__get_packed_size
                     (const Yoke__Interface__V1__Refusal   *message);
size_t yoke__interface__v1__refusal__pack
                     (const Yoke__Interface__V1__Refusal   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__refusal__pack_to_buffer
                     (const Yoke__Interface__V1__Refusal   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Refusal *
       yoke__interface__v1__refusal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__refusal__free_unpacked
                     (Yoke__Interface__V1__Refusal *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Subject methods */
void   yoke__interface__v1__subject__init
                     (Yoke__Interface__V1__Subject         *message);
size_t yoke__interface__v1__subject__get_packed_size
                     (const Yoke__Interface__V1__Subject   *message);
size_t yoke__interface__v1__subject__pack
                     (const Yoke__Interface__V1__Subject   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__subject__pack_to_buffer
                     (const Yoke__Interface__V1__Subject   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Subject *
       yoke__interface__v1__subject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__subject__free_unpacked
                     (Yoke__Interface__V1__Subject *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Suspension methods */
void   yoke__interface__v1__suspension__init
                     (Yoke__Interface__V1__Suspension         *message);
size_t yoke__interface__v1__suspension__get_packed_size
                     (const Yoke__Interface__V1__Suspension   *message);
size_t yoke__interface__v1__suspension__pack
                     (const Yoke__Interface__V1__Suspension   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__suspension__pack_to_buffer
                     (const Yoke__Interface__V1__Suspension   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Suspension *
       yoke__interface__v1__suspension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__suspension__free_unpacked
                     (Yoke__Interface__V1__Suspension *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Interface__V1__Refusal_Closure)
                 (const Yoke__Interface__V1__Refusal *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Subject_Closure)
                 (const Yoke__Interface__V1__Subject *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Suspension_Closure)
                 (const Yoke__Interface__V1__Suspension *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    yoke__interface__v1__code__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__refusal__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__subject__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__suspension__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2fcodes_2eproto__INCLUDED */
