/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/codes.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/interface/v1/codes.pb-c.h"
void   yoke__interface__v1__refusal__init
                     (Yoke__Interface__V1__Refusal         *message)
{
  static const Yoke__Interface__V1__Refusal init_value = YOKE__INTERFACE__V1__REFUSAL__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__refusal__get_packed_size
                     (const Yoke__Interface__V1__Refusal *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__refusal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__refusal__pack
                     (const Yoke__Interface__V1__Refusal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__refusal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__refusal__pack_to_buffer
                     (const Yoke__Interface__V1__Refusal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__refusal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Refusal *
       yoke__interface__v1__refusal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Refusal *)
     protobuf_c_message_unpack (&yoke__interface__v1__refusal__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__refusal__free_unpacked
                     (Yoke__Interface__V1__Refusal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__refusal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__subject__init
                     (Yoke__Interface__V1__Subject         *message)
{
  static const Yoke__Interface__V1__Subject init_value = YOKE__INTERFACE__V1__SUBJECT__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__subject__get_packed_size
                     (const Yoke__Interface__V1__Subject *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__subject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__subject__pack
                     (const Yoke__Interface__V1__Subject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__subject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__subject__pack_to_buffer
                     (const Yoke__Interface__V1__Subject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__subject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Subject *
       yoke__interface__v1__subject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Subject *)
     protobuf_c_message_unpack (&yoke__interface__v1__subject__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__subject__free_unpacked
                     (Yoke__Interface__V1__Subject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__subject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__suspension__init
                     (Yoke__Interface__V1__Suspension         *message)
{
  static const Yoke__Interface__V1__Suspension init_value = YOKE__INTERFACE__V1__SUSPENSION__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__suspension__get_packed_size
                     (const Yoke__Interface__V1__Suspension *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__suspension__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__suspension__pack
                     (const Yoke__Interface__V1__Suspension *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__suspension__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__suspension__pack_to_buffer
                     (const Yoke__Interface__V1__Suspension *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__suspension__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Suspension *
       yoke__interface__v1__suspension__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Suspension *)
     protobuf_c_message_unpack (&yoke__interface__v1__suspension__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__suspension__free_unpacked
                     (Yoke__Interface__V1__Suspension *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__suspension__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__interface__v1__refusal__field_descriptors[5] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Refusal, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Refusal, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Refusal, detail_case),
    offsetof(Yoke__Interface__V1__Refusal, subject),
    &yoke__interface__v1__subject__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__Refusal, detail_case),
    offsetof(Yoke__Interface__V1__Refusal, item),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suspension",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Refusal, detail_case),
    offsetof(Yoke__Interface__V1__Refusal, suspension),
    &yoke__interface__v1__suspension__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__refusal__field_indices_by_name[] = {
  0,   /* field[0] = code */
  3,   /* field[3] = item */
  1,   /* field[1] = message */
  2,   /* field[2] = subject */
  4,   /* field[4] = suspension */
};
static const ProtobufCIntRange yoke__interface__v1__refusal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__refusal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Refusal",
  "Refusal",
  "Yoke__Interface__V1__Refusal",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Refusal),
  5,
  yoke__interface__v1__refusal__field_descriptors,
  yoke__interface__v1__refusal__field_indices_by_name,
  1,  yoke__interface__v1__refusal__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__refusal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__subject__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Subject, kind),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Subject, identity),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incarnation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Subject, incarnation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__subject__field_indices_by_name[] = {
  1,   /* field[1] = identity */
  2,   /* field[2] = incarnation */
  0,   /* field[0] = kind */
};
static const ProtobufCIntRange yoke__interface__v1__subject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__subject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Subject",
  "Subject",
  "Yoke__Interface__V1__Subject",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Subject),
  3,
  yoke__interface__v1__subject__field_descriptors,
  yoke__interface__v1__subject__field_indices_by_name,
  1,  yoke__interface__v1__subject__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__subject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__suspension__field_descriptors[2] =
{
  {
    "grade",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Suspension, grade),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "by",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Suspension, by),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__suspension__field_indices_by_name[] = {
  1,   /* field[1] = by */
  0,   /* field[0] = grade */
};
static const ProtobufCIntRange yoke__interface__v1__suspension__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__suspension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Suspension",
  "Suspension",
  "Yoke__Interface__V1__Suspension",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Suspension),
  2,
  yoke__interface__v1__suspension__field_descriptors,
  yoke__interface__v1__suspension__field_indices_by_name,
  1,  yoke__interface__v1__suspension__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__suspension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__interface__v1__code__enum_values_by_number[18] =
{
  { "CODE_UNSPECIFIED", "YOKE__INTERFACE__V1__CODE__CODE_UNSPECIFIED", 0 },
  { "CODE_OPERATION_MALFORMED", "YOKE__INTERFACE__V1__CODE__CODE_OPERATION_MALFORMED", 1 },
  { "CODE_OPERATION_UNKNOWN", "YOKE__INTERFACE__V1__CODE__CODE_OPERATION_UNKNOWN", 2 },
  { "CODE_COMPAT_UNSUPPORTED", "YOKE__INTERFACE__V1__CODE__CODE_COMPAT_UNSUPPORTED", 3 },
  { "CODE_AUTH_REQUIRED", "YOKE__INTERFACE__V1__CODE__CODE_AUTH_REQUIRED", 4 },
  { "CODE_AUTH_INVALID", "YOKE__INTERFACE__V1__CODE__CODE_AUTH_INVALID", 5 },
  { "CODE_CHANNEL_IN_USE", "YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_IN_USE", 6 },
  { "CODE_CHANNEL_NOT_ATTACHED", "YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_NOT_ATTACHED", 7 },
  { "CODE_CHANNEL_SUSPENDED", "YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_SUSPENDED", 8 },
  { "CODE_CHANNEL_NOT_LOCAL", "YOKE__INTERFACE__V1__CODE__CODE_CHANNEL_NOT_LOCAL", 9 },
  { "CODE_SUBJECT_UNKNOWN", "YOKE__INTERFACE__V1__CODE__CODE_SUBJECT_UNKNOWN", 10 },
  { "CODE_SCOPE_UNDECLARED", "YOKE__INTERFACE__V1__CODE__CODE_SCOPE_UNDECLARED", 11 },
  { "CODE_SCOPE_WITHHELD", "YOKE__INTERFACE__V1__CODE__CODE_SCOPE_WITHHELD", 12 },
  { "CODE_UNIT_NOT_RUNNING", "YOKE__INTERFACE__V1__CODE__CODE_UNIT_NOT_RUNNING", 13 },
  { "CODE_UNIT_NO_SESSION", "YOKE__INTERFACE__V1__CODE__CODE_UNIT_NO_SESSION", 14 },
  { "CODE_UNIT_UNANSWERED", "YOKE__INTERFACE__V1__CODE__CODE_UNIT_UNANSWERED", 15 },
  { "CODE_INSTANCE_STOPPING", "YOKE__INTERFACE__V1__CODE__CODE_INSTANCE_STOPPING", 16 },
  { "CODE_UNIT_FAILED", "YOKE__INTERFACE__V1__CODE__CODE_UNIT_FAILED", 17 },
};
static const ProtobufCIntRange yoke__interface__v1__code__value_ranges[] = {
{0, 0},{0, 18}
};
static const ProtobufCEnumValueIndex yoke__interface__v1__code__enum_values_by_name[18] =
{
  { "CODE_AUTH_INVALID", 5 },
  { "CODE_AUTH_REQUIRED", 4 },
  { "CODE_CHANNEL_IN_USE", 6 },
  { "CODE_CHANNEL_NOT_ATTACHED", 7 },
  { "CODE_CHANNEL_NOT_LOCAL", 9 },
  { "CODE_CHANNEL_SUSPENDED", 8 },
  { "CODE_COMPAT_UNSUPPORTED", 3 },
  { "CODE_INSTANCE_STOPPING", 16 },
  { "CODE_OPERATION_MALFORMED", 1 },
  { "CODE_OPERATION_UNKNOWN", 2 },
  { "CODE_SCOPE_UNDECLARED", 11 },
  { "CODE_SCOPE_WITHHELD", 12 },
  { "CODE_SUBJECT_UNKNOWN", 10 },
  { "CODE_UNIT_FAILED", 17 },
  { "CODE_UNIT_NOT_RUNNING", 13 },
  { "CODE_UNIT_NO_SESSION", 14 },
  { "CODE_UNIT_UNANSWERED", 15 },
  { "CODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__interface__v1__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Code",
  "Code",
  "Yoke__Interface__V1__Code",
  "yoke.interface.v1",
  18,
  yoke__interface__v1__code__enum_values_by_number,
  18,
  yoke__interface__v1__code__enum_values_by_name,
  1,
  yoke__interface__v1__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
