/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/contract.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2fcontract_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2fcontract_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Yoke__Interface__V1__Contract {
  YOKE__INTERFACE__V1__CONTRACT__CONTRACT_UNSPECIFIED = 0,
  YOKE__INTERFACE__V1__CONTRACT__CONTRACT_VERSION = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__CONTRACT)
} Yoke__Interface__V1__Contract;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    yoke__interface__v1__contract__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2fcontract_2eproto__INCLUDED */
