/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/events.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/interface/v1/events.pb-c.h"
void   yoke__interface__v1__event__init
                     (Yoke__Interface__V1__Event         *message)
{
  static const Yoke__Interface__V1__Event init_value = YOKE__INTERFACE__V1__EVENT__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__event__get_packed_size
                     (const Yoke__Interface__V1__Event *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__event__pack
                     (const Yoke__Interface__V1__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__event__pack_to_buffer
                     (const Yoke__Interface__V1__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Event *
       yoke__interface__v1__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Event *)
     protobuf_c_message_unpack (&yoke__interface__v1__event__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__event__free_unpacked
                     (Yoke__Interface__V1__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__actor__init
                     (Yoke__Interface__V1__Actor         *message)
{
  static const Yoke__Interface__V1__Actor init_value = YOKE__INTERFACE__V1__ACTOR__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__actor__get_packed_size
                     (const Yoke__Interface__V1__Actor *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__actor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__actor__pack
                     (const Yoke__Interface__V1__Actor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__actor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__actor__pack_to_buffer
                     (const Yoke__Interface__V1__Actor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__actor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Actor *
       yoke__interface__v1__actor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Actor *)
     protobuf_c_message_unpack (&yoke__interface__v1__actor__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__actor__free_unpacked
                     (Yoke__Interface__V1__Actor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__actor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__filter__init
                     (Yoke__Interface__V1__Filter         *message)
{
  static const Yoke__Interface__V1__Filter init_value = YOKE__INTERFACE__V1__FILTER__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__filter__get_packed_size
                     (const Yoke__Interface__V1__Filter *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__filter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__filter__pack
                     (const Yoke__Interface__V1__Filter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__filter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__filter__pack_to_buffer
                     (const Yoke__Interface__V1__Filter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__filter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Filter *
       yoke__interface__v1__filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Filter *)
     protobuf_c_message_unpack (&yoke__interface__v1__filter__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__filter__free_unpacked
                     (Yoke__Interface__V1__Filter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__filter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__interface__v1__event__field_descriptors[9] =
{
  {
    "seq",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, subject),
    &yoke__interface__v1__subject__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, time),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actor",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, actor),
    &yoke__interface__v1__actor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, severity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occurrence",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, occurrence),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cause",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, cause),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detail",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Event, detail),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__event__field_indices_by_name[] = {
  4,   /* field[4] = actor */
  7,   /* field[7] = cause */
  8,   /* field[8] = detail */
  6,   /* field[6] = occurrence */
  0,   /* field[0] = seq */
  5,   /* field[5] = severity */
  2,   /* field[2] = subject */
  3,   /* field[3] = time */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange yoke__interface__v1__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Event",
  "Event",
  "Yoke__Interface__V1__Event",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Event),
  9,
  yoke__interface__v1__event__field_descriptors,
  yoke__interface__v1__event__field_indices_by_name,
  1,  yoke__interface__v1__event__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__actor__field_descriptors[2] =
{
  {
    "class",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Actor, class_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "person",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Actor, person),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__actor__field_indices_by_name[] = {
  0,   /* field[0] = class */
  1,   /* field[1] = person */
};
static const ProtobufCIntRange yoke__interface__v1__actor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__actor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Actor",
  "Actor",
  "Yoke__Interface__V1__Actor",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Actor),
  2,
  yoke__interface__v1__actor__field_descriptors,
  yoke__interface__v1__actor__field_indices_by_name,
  1,  yoke__interface__v1__actor__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__actor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__filter__field_descriptors[7] =
{
  {
    "subject_kind",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, subject_kind),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject_identity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, subject_identity),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "floor",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, floor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type_prefix",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, type_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occurrence",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, occurrence),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occurrence_prefix",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Filter, occurrence_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__filter__field_indices_by_name[] = {
  2,   /* field[2] = floor */
  5,   /* field[5] = occurrence */
  6,   /* field[6] = occurrence_prefix */
  1,   /* field[1] = subject_identity */
  0,   /* field[0] = subject_kind */
  3,   /* field[3] = type */
  4,   /* field[4] = type_prefix */
};
static const ProtobufCIntRange yoke__interface__v1__filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Filter",
  "Filter",
  "Yoke__Interface__V1__Filter",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Filter),
  7,
  yoke__interface__v1__filter__field_descriptors,
  yoke__interface__v1__filter__field_indices_by_name,
  1,  yoke__interface__v1__filter__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
