/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/events.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2fevents_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2fevents_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"
#include "yoke/interface/v1/codes.pb-c.h"

typedef struct Yoke__Interface__V1__Event Yoke__Interface__V1__Event;
typedef struct Yoke__Interface__V1__Actor Yoke__Interface__V1__Actor;
typedef struct Yoke__Interface__V1__Filter Yoke__Interface__V1__Filter;


/* --- enums --- */


/* --- messages --- */

/*
 * One conclusion the Core reached: eight fields, the same on every event and on every surface.
 */
struct  Yoke__Interface__V1__Event
{
  ProtobufCMessage base;
  /*
   * Numbers the event within one life of the instance; what a snapshot's sequence, a confirmation and a
   * cause refer to.
   */
  uint64_t seq;
  /*
   * What happened: <subject-kind>.<object>.<verb>, and what a subscription filters on.
   */
  char *type;
  Yoke__Interface__V1__Subject *subject;
  /*
   * The Core's clock, at the conclusion.
   */
  Google__Protobuf__Timestamp *time;
  Yoke__Interface__V1__Actor *actor;
  /*
   * 0 to 99, higher more serious.
   */
  uint32_t severity;
  /*
   * The class a unit declared and was granted, on unit.occurrence.reported alone.
   */
  char *occurrence;
  /*
   * The event this one follows from; zero where there is none.
   */
  uint64_t cause;
  /*
   * Typed per type, and skippable: a consumer decodes only what it knows.
   */
  ProtobufCBinaryData detail;
};
#define YOKE__INTERFACE__V1__EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__event__descriptor) \
    , 0, (char *)protobuf_c_empty_string, NULL, NULL, NULL, 0, (char *)protobuf_c_empty_string, 0, {0,NULL} }


/*
 * Who caused an event, established by the Core and never claimed.
 */
struct  Yoke__Interface__V1__Actor
{
  ProtobufCMessage base;
  /*
   * core, operator, unit or host: four, closed.
   */
  char *class_;
  /*
   * The person the channel established, where it established one.
   */
  char *person;
};
#define YOKE__INTERFACE__V1__ACTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__actor__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * What a subscription selects, on four independent axes combined by conjunction. An axis left empty
 * selects everything on it, and a kind this channel does not observe matches nothing.
 */
struct  Yoke__Interface__V1__Filter
{
  ProtobufCMessage base;
  /*
   * A subject kind, and an identity where one is named.
   */
  char *subject_kind;
  char *subject_identity;
  /*
   * At or above.
   */
  uint32_t floor;
  /*
   * Exactly, or by prefix of segments.
   */
  char *type;
  protobuf_c_boolean type_prefix;
  /*
   * Exactly, or by prefix of segments; reaches only the events that carry one.
   */
  char *occurrence;
  protobuf_c_boolean occurrence_prefix;
};
#define YOKE__INTERFACE__V1__FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__filter__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0 }


/* Yoke__Interface__V1__Event methods */
void   yoke__interface__v1__event__init
                     (Yoke__Interface__V1__Event         *message);
size_t yoke__interface__v1__event__get_packed_size
                     (const Yoke__Interface__V1__Event   *message);
size_t yoke__interface__v1__event__pack
                     (const Yoke__Interface__V1__Event   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__event__pack_to_buffer
                     (const Yoke__Interface__V1__Event   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Event *
       yoke__interface__v1__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__event__free_unpacked
                     (Yoke__Interface__V1__Event *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Actor methods */
void   yoke__interface__v1__actor__init
                     (Yoke__Interface__V1__Actor         *message);
size_t yoke__interface__v1__actor__get_packed_size
                     (const Yoke__Interface__V1__Actor   *message);
size_t yoke__interface__v1__actor__pack
                     (const Yoke__Interface__V1__Actor   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__actor__pack_to_buffer
                     (const Yoke__Interface__V1__Actor   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Actor *
       yoke__interface__v1__actor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__actor__free_unpacked
                     (Yoke__Interface__V1__Actor *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Filter methods */
void   yoke__interface__v1__filter__init
                     (Yoke__Interface__V1__Filter         *message);
size_t yoke__interface__v1__filter__get_packed_size
                     (const Yoke__Interface__V1__Filter   *message);
size_t yoke__interface__v1__filter__pack
                     (const Yoke__Interface__V1__Filter   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__filter__pack_to_buffer
                     (const Yoke__Interface__V1__Filter   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Filter *
       yoke__interface__v1__filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__filter__free_unpacked
                     (Yoke__Interface__V1__Filter *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Interface__V1__Event_Closure)
                 (const Yoke__Interface__V1__Event *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Actor_Closure)
                 (const Yoke__Interface__V1__Actor *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Filter_Closure)
                 (const Yoke__Interface__V1__Filter *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__interface__v1__event__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__actor__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__filter__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2fevents_2eproto__INCLUDED */
