/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/interface.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "yoke/interface/v1/codes.pb-c.h"
#include "yoke/interface/v1/events.pb-c.h"
#include "yoke/interface/v1/operations.pb-c.h"
#include "yoke/interface/v1/records.pb-c.h"

typedef struct Yoke__Interface__V1__ClientFrame Yoke__Interface__V1__ClientFrame;
typedef struct Yoke__Interface__V1__Cancel Yoke__Interface__V1__Cancel;
typedef struct Yoke__Interface__V1__CoreFrame Yoke__Interface__V1__CoreFrame;
typedef struct Yoke__Interface__V1__Opening Yoke__Interface__V1__Opening;
typedef struct Yoke__Interface__V1__StreamDelivery Yoke__Interface__V1__StreamDelivery;
typedef struct Yoke__Interface__V1__Completion Yoke__Interface__V1__Completion;


/* --- enums --- */

typedef enum _Yoke__Interface__V1__Completion__By {
  YOKE__INTERFACE__V1__COMPLETION__BY__BY_UNSPECIFIED = 0,
  /*
   * The caller cancelled it.
   */
  YOKE__INTERFACE__V1__COMPLETION__BY__BY_CALLER = 1,
  /*
   * The Core ended it.
   */
  YOKE__INTERFACE__V1__COMPLETION__BY__BY_CORE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__COMPLETION__BY)
} Yoke__Interface__V1__Completion__By;

/* --- messages --- */

typedef enum {
  YOKE__INTERFACE__V1__CLIENT_FRAME__CARRIES__NOT_SET = 0,
  YOKE__INTERFACE__V1__CLIENT_FRAME__CARRIES_REQUEST = 2,
  YOKE__INTERFACE__V1__CLIENT_FRAME__CARRIES_CANCEL = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__CLIENT_FRAME__CARRIES__CASE)
} Yoke__Interface__V1__ClientFrame__CarriesCase;

struct  Yoke__Interface__V1__ClientFrame
{
  ProtobufCMessage base;
  /*
   * Chosen by the caller, unique within this attachment.
   */
  char *call;
  Yoke__Interface__V1__ClientFrame__CarriesCase carries_case;
  union {
    Yoke__Interface__V1__Request *request;
    Yoke__Interface__V1__Cancel *cancel;
  };
};
#define YOKE__INTERFACE__V1__CLIENT_FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__client_frame__descriptor) \
    , (char *)protobuf_c_empty_string, YOKE__INTERFACE__V1__CLIENT_FRAME__CARRIES__NOT_SET, {0} }


/*
 * Ends a call in flight.
 */
struct  Yoke__Interface__V1__Cancel
{
  ProtobufCMessage base;
};
#define YOKE__INTERFACE__V1__CANCEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__cancel__descriptor) \
     }


typedef enum {
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES__NOT_SET = 0,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_OPENING = 2,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_ANSWER = 3,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_EVENT = 4,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_DELIVERY = 5,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_REFUSAL = 6,
  YOKE__INTERFACE__V1__CORE_FRAME__CARRIES_COMPLETION = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__CORE_FRAME__CARRIES__CASE)
} Yoke__Interface__V1__CoreFrame__CarriesCase;

struct  Yoke__Interface__V1__CoreFrame
{
  ProtobufCMessage base;
  /*
   * The call this frame belongs to; empty on the opening.
   */
  char *call;
  Yoke__Interface__V1__CoreFrame__CarriesCase carries_case;
  union {
    Yoke__Interface__V1__Opening *opening;
    Yoke__Interface__V1__Response *answer;
    Yoke__Interface__V1__Event *event;
    /*
     * A stream's data, where the client cannot reach a path in the instance's tree.
     */
    Yoke__Interface__V1__StreamDelivery *delivery;
    /*
     * A refusal belongs to one call and does not end the attachment.
     */
    Yoke__Interface__V1__Refusal *refusal;
    Yoke__Interface__V1__Completion *completion;
  };
};
#define YOKE__INTERFACE__V1__CORE_FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__core_frame__descriptor) \
    , (char *)protobuf_c_empty_string, YOKE__INTERFACE__V1__CORE_FRAME__CARRIES__NOT_SET, {0} }


/*
 * The Core's first frame: the opening picture, before anything the client asked for.
 */
struct  Yoke__Interface__V1__Opening
{
  ProtobufCMessage base;
  /*
   * What this channel may address and observe, the state of each, and the channel's own state.
   */
  Yoke__Interface__V1__Snapshot *picture;
  /*
   * The call identity of the standing subscription, which the client may replace or cancel.
   */
  char *subscription;
  /*
   * The contract version this Core speaks.
   */
  uint32_t version;
};
#define YOKE__INTERFACE__V1__OPENING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__opening__descriptor) \
    , NULL, (char *)protobuf_c_empty_string, 0 }


/*
 * A stream's data on the connection: the delivery, and the frame's header and payload unchanged.
 */
struct  Yoke__Interface__V1__StreamDelivery
{
  ProtobufCMessage base;
  char *delivery;
  /*
   * Per stream, from 1, never reused within an activation.
   */
  uint64_t sequence;
  /*
   * The sender's clock at emission, in nanoseconds.
   */
  uint64_t sent_at;
  ProtobufCBinaryData payload;
};
#define YOKE__INTERFACE__V1__STREAM_DELIVERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__stream_delivery__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, {0,NULL} }


/*
 * The end of a call; never inferred from silence.
 */
struct  Yoke__Interface__V1__Completion
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Completion__By by;
};
#define YOKE__INTERFACE__V1__COMPLETION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__completion__descriptor) \
    , YOKE__INTERFACE__V1__COMPLETION__BY__BY_UNSPECIFIED }


/* Yoke__Interface__V1__ClientFrame methods */
void   yoke__interface__v1__client_frame__init
                     (Yoke__Interface__V1__ClientFrame         *message);
size_t yoke__interface__v1__client_frame__get_packed_size
                     (const Yoke__Interface__V1__ClientFrame   *message);
size_t yoke__interface__v1__client_frame__pack
                     (const Yoke__Interface__V1__ClientFrame   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__client_frame__pack_to_buffer
                     (const Yoke__Interface__V1__ClientFrame   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__ClientFrame *
       yoke__interface__v1__client_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__client_frame__free_unpacked
                     (Yoke__Interface__V1__ClientFrame *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Cancel methods */
void   yoke__interface__v1__cancel__init
                     (Yoke__Interface__V1__Cancel         *message);
size_t yoke__interface__v1__cancel__get_packed_size
                     (const Yoke__Interface__V1__Cancel   *message);
size_t yoke__interface__v1__cancel__pack
                     (const Yoke__Interface__V1__Cancel   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__cancel__pack_to_buffer
                     (const Yoke__Interface__V1__Cancel   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Cancel *
       yoke__interface__v1__cancel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__cancel__free_unpacked
                     (Yoke__Interface__V1__Cancel *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__CoreFrame methods */
void   yoke__interface__v1__core_frame__init
                     (Yoke__Interface__V1__CoreFrame         *message);
size_t yoke__interface__v1__core_frame__get_packed_size
                     (const Yoke__Interface__V1__CoreFrame   *message);
size_t yoke__interface__v1__core_frame__pack
                     (const Yoke__Interface__V1__CoreFrame   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__core_frame__pack_to_buffer
                     (const Yoke__Interface__V1__CoreFrame   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__CoreFrame *
       yoke__interface__v1__core_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__core_frame__free_unpacked
                     (Yoke__Interface__V1__CoreFrame *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Opening methods */
void   yoke__interface__v1__opening__init
                     (Yoke__Interface__V1__Opening         *message);
size_t yoke__interface__v1__opening__get_packed_size
                     (const Yoke__Interface__V1__Opening   *message);
size_t yoke__interface__v1__opening__pack
                     (const Yoke__Interface__V1__Opening   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__opening__pack_to_buffer
                     (const Yoke__Interface__V1__Opening   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Opening *
       yoke__interface__v1__opening__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__opening__free_unpacked
                     (Yoke__Interface__V1__Opening *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__StreamDelivery methods */
void   yoke__interface__v1__stream_delivery__init
                     (Yoke__Interface__V1__StreamDelivery         *message);
size_t yoke__interface__v1__stream_delivery__get_packed_size
                     (const Yoke__Interface__V1__StreamDelivery   *message);
size_t yoke__interface__v1__stream_delivery__pack
                     (const Yoke__Interface__V1__StreamDelivery   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__stream_delivery__pack_to_buffer
                     (const Yoke__Interface__V1__StreamDelivery   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__StreamDelivery *
       yoke__interface__v1__stream_delivery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__stream_delivery__free_unpacked
                     (Yoke__Interface__V1__StreamDelivery *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Completion methods */
void   yoke__interface__v1__completion__init
                     (Yoke__Interface__V1__Completion         *message);
size_t yoke__interface__v1__completion__get_packed_size
                     (const Yoke__Interface__V1__Completion   *message);
size_t yoke__interface__v1__completion__pack
                     (const Yoke__Interface__V1__Completion   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__completion__pack_to_buffer
                     (const Yoke__Interface__V1__Completion   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Completion *
       yoke__interface__v1__completion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__completion__free_unpacked
                     (Yoke__Interface__V1__Completion *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Interface__V1__ClientFrame_Closure)
                 (const Yoke__Interface__V1__ClientFrame *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Cancel_Closure)
                 (const Yoke__Interface__V1__Cancel *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__CoreFrame_Closure)
                 (const Yoke__Interface__V1__CoreFrame *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Opening_Closure)
                 (const Yoke__Interface__V1__Opening *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__StreamDelivery_Closure)
                 (const Yoke__Interface__V1__StreamDelivery *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Completion_Closure)
                 (const Yoke__Interface__V1__Completion *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__interface__v1__client_frame__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__cancel__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__core_frame__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__opening__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__stream_delivery__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__completion__descriptor;
extern const ProtobufCEnumDescriptor    yoke__interface__v1__completion__by__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED */
