/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/interface.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/interface/v1/interface.pb-c.h"
void   yoke__interface__v1__client_frame__init
                     (Yoke__Interface__V1__ClientFrame         *message)
{
  static const Yoke__Interface__V1__ClientFrame init_value = YOKE__INTERFACE__V1__CLIENT_FRAME__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__client_frame__get_packed_size
                     (const Yoke__Interface__V1__ClientFrame *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__client_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__client_frame__pack
                     (const Yoke__Interface__V1__ClientFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__client_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__client_frame__pack_to_buffer
                     (const Yoke__Interface__V1__ClientFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__client_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__ClientFrame *
       yoke__interface__v1__client_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__ClientFrame *)
     protobuf_c_message_unpack (&yoke__interface__v1__client_frame__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__client_frame__free_unpacked
                     (Yoke__Interface__V1__ClientFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__client_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__cancel__init
                     (Yoke__Interface__V1__Cancel         *message)
{
  static const Yoke__Interface__V1__Cancel init_value = YOKE__INTERFACE__V1__CANCEL__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__cancel__get_packed_size
                     (const Yoke__Interface__V1__Cancel *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__cancel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__cancel__pack
                     (const Yoke__Interface__V1__Cancel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__cancel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__cancel__pack_to_buffer
                     (const Yoke__Interface__V1__Cancel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__cancel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Cancel *
       yoke__interface__v1__cancel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Cancel *)
     protobuf_c_message_unpack (&yoke__interface__v1__cancel__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__cancel__free_unpacked
                     (Yoke__Interface__V1__Cancel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__cancel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__core_frame__init
                     (Yoke__Interface__V1__CoreFrame         *message)
{
  static const Yoke__Interface__V1__CoreFrame init_value = YOKE__INTERFACE__V1__CORE_FRAME__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__core_frame__get_packed_size
                     (const Yoke__Interface__V1__CoreFrame *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__core_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__core_frame__pack
                     (const Yoke__Interface__V1__CoreFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__core_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__core_frame__pack_to_buffer
                     (const Yoke__Interface__V1__CoreFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__core_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__CoreFrame *
       yoke__interface__v1__core_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__CoreFrame *)
     protobuf_c_message_unpack (&yoke__interface__v1__core_frame__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__core_frame__free_unpacked
                     (Yoke__Interface__V1__CoreFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__core_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__opening__init
                     (Yoke__Interface__V1__Opening         *message)
{
  static const Yoke__Interface__V1__Opening init_value = YOKE__INTERFACE__V1__OPENING__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__opening__get_packed_size
                     (const Yoke__Interface__V1__Opening *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__opening__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__opening__pack
                     (const Yoke__Interface__V1__Opening *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__opening__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__opening__pack_to_buffer
                     (const Yoke__Interface__V1__Opening *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__opening__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Opening *
       yoke__interface__v1__opening__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Opening *)
     protobuf_c_message_unpack (&yoke__interface__v1__opening__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__opening__free_unpacked
                     (Yoke__Interface__V1__Opening *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__opening__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__stream_delivery__init
                     (Yoke__Interface__V1__StreamDelivery         *message)
{
  static const Yoke__Interface__V1__StreamDelivery init_value = YOKE__INTERFACE__V1__STREAM_DELIVERY__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__stream_delivery__get_packed_size
                     (const Yoke__Interface__V1__StreamDelivery *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_delivery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__stream_delivery__pack
                     (const Yoke__Interface__V1__StreamDelivery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_delivery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__stream_delivery__pack_to_buffer
                     (const Yoke__Interface__V1__StreamDelivery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_delivery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__StreamDelivery *
       yoke__interface__v1__stream_delivery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__StreamDelivery *)
     protobuf_c_message_unpack (&yoke__interface__v1__stream_delivery__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__stream_delivery__free_unpacked
                     (Yoke__Interface__V1__StreamDelivery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__stream_delivery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__completion__init
                     (Yoke__Interface__V1__Completion         *message)
{
  static const Yoke__Interface__V1__Completion init_value = YOKE__INTERFACE__V1__COMPLETION__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__completion__get_packed_size
                     (const Yoke__Interface__V1__Completion *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__completion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__completion__pack
                     (const Yoke__Interface__V1__Completion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__completion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__completion__pack_to_buffer
                     (const Yoke__Interface__V1__Completion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__completion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Completion *
       yoke__interface__v1__completion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Completion *)
     protobuf_c_message_unpack (&yoke__interface__v1__completion__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__completion__free_unpacked
                     (Yoke__Interface__V1__Completion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__completion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__interface__v1__client_frame__field_descriptors[3] =
{
  {
    "call",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ClientFrame, call),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__ClientFrame, carries_case),
    offsetof(Yoke__Interface__V1__ClientFrame, request),
    &yoke__interface__v1__request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cancel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__ClientFrame, carries_case),
    offsetof(Yoke__Interface__V1__ClientFrame, cancel),
    &yoke__interface__v1__cancel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__client_frame__field_indices_by_name[] = {
  0,   /* field[0] = call */
  2,   /* field[2] = cancel */
  1,   /* field[1] = request */
};
static const ProtobufCIntRange yoke__interface__v1__client_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__client_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.ClientFrame",
  "ClientFrame",
  "Yoke__Interface__V1__ClientFrame",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__ClientFrame),
  3,
  yoke__interface__v1__client_frame__field_descriptors,
  yoke__interface__v1__client_frame__field_indices_by_name,
  1,  yoke__interface__v1__client_frame__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__client_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define yoke__interface__v1__cancel__field_descriptors NULL
#define yoke__interface__v1__cancel__field_indices_by_name NULL
#define yoke__interface__v1__cancel__number_ranges NULL
const ProtobufCMessageDescriptor yoke__interface__v1__cancel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Cancel",
  "Cancel",
  "Yoke__Interface__V1__Cancel",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Cancel),
  0,
  yoke__interface__v1__cancel__field_descriptors,
  yoke__interface__v1__cancel__field_indices_by_name,
  0,  yoke__interface__v1__cancel__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__cancel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__core_frame__field_descriptors[7] =
{
  {
    "call",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__CoreFrame, call),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opening",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, opening),
    &yoke__interface__v1__opening__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "answer",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, answer),
    &yoke__interface__v1__response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, event),
    &yoke__interface__v1__event__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delivery",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, delivery),
    &yoke__interface__v1__stream_delivery__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refusal",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, refusal),
    &yoke__interface__v1__refusal__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "completion",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__CoreFrame, carries_case),
    offsetof(Yoke__Interface__V1__CoreFrame, completion),
    &yoke__interface__v1__completion__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__core_frame__field_indices_by_name[] = {
  2,   /* field[2] = answer */
  0,   /* field[0] = call */
  6,   /* field[6] = completion */
  4,   /* field[4] = delivery */
  3,   /* field[3] = event */
  1,   /* field[1] = opening */
  5,   /* field[5] = refusal */
};
static const ProtobufCIntRange yoke__interface__v1__core_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__core_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.CoreFrame",
  "CoreFrame",
  "Yoke__Interface__V1__CoreFrame",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__CoreFrame),
  7,
  yoke__interface__v1__core_frame__field_descriptors,
  yoke__interface__v1__core_frame__field_indices_by_name,
  1,  yoke__interface__v1__core_frame__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__core_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__opening__field_descriptors[3] =
{
  {
    "picture",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Opening, picture),
    &yoke__interface__v1__snapshot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscription",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Opening, subscription),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Opening, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__opening__field_indices_by_name[] = {
  0,   /* field[0] = picture */
  1,   /* field[1] = subscription */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange yoke__interface__v1__opening__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__opening__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Opening",
  "Opening",
  "Yoke__Interface__V1__Opening",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Opening),
  3,
  yoke__interface__v1__opening__field_descriptors,
  yoke__interface__v1__opening__field_indices_by_name,
  1,  yoke__interface__v1__opening__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__opening__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__stream_delivery__field_descriptors[4] =
{
  {
    "delivery",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__StreamDelivery, delivery),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__StreamDelivery, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sent_at",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__StreamDelivery, sent_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__StreamDelivery, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__stream_delivery__field_indices_by_name[] = {
  0,   /* field[0] = delivery */
  3,   /* field[3] = payload */
  2,   /* field[2] = sent_at */
  1,   /* field[1] = sequence */
};
static const ProtobufCIntRange yoke__interface__v1__stream_delivery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__stream_delivery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.StreamDelivery",
  "StreamDelivery",
  "Yoke__Interface__V1__StreamDelivery",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__StreamDelivery),
  4,
  yoke__interface__v1__stream_delivery__field_descriptors,
  yoke__interface__v1__stream_delivery__field_indices_by_name,
  1,  yoke__interface__v1__stream_delivery__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__stream_delivery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__interface__v1__completion__by__enum_values_by_number[3] =
{
  { "BY_UNSPECIFIED", "YOKE__INTERFACE__V1__COMPLETION__BY__BY_UNSPECIFIED", 0 },
  { "BY_CALLER", "YOKE__INTERFACE__V1__COMPLETION__BY__BY_CALLER", 1 },
  { "BY_CORE", "YOKE__INTERFACE__V1__COMPLETION__BY__BY_CORE", 2 },
};
static const ProtobufCIntRange yoke__interface__v1__completion__by__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex yoke__interface__v1__completion__by__enum_values_by_name[3] =
{
  { "BY_CALLER", 1 },
  { "BY_CORE", 2 },
  { "BY_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__interface__v1__completion__by__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Completion.By",
  "By",
  "Yoke__Interface__V1__Completion__By",
  "yoke.interface.v1",
  3,
  yoke__interface__v1__completion__by__enum_values_by_number,
  3,
  yoke__interface__v1__completion__by__enum_values_by_name,
  1,
  yoke__interface__v1__completion__by__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__completion__field_descriptors[1] =
{
  {
    "by",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Completion, by),
    &yoke__interface__v1__completion__by__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__completion__field_indices_by_name[] = {
  0,   /* field[0] = by */
};
static const ProtobufCIntRange yoke__interface__v1__completion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__completion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Completion",
  "Completion",
  "Yoke__Interface__V1__Completion",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Completion),
  1,
  yoke__interface__v1__completion__field_descriptors,
  yoke__interface__v1__completion__field_indices_by_name,
  1,  yoke__interface__v1__completion__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__completion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
