/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/operations.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/interface/v1/operations.pb-c.h"
void   yoke__interface__v1__request__init
                     (Yoke__Interface__V1__Request         *message)
{
  static const Yoke__Interface__V1__Request init_value = YOKE__INTERFACE__V1__REQUEST__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__request__get_packed_size
                     (const Yoke__Interface__V1__Request *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__request__pack
                     (const Yoke__Interface__V1__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__request__pack_to_buffer
                     (const Yoke__Interface__V1__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Request *
       yoke__interface__v1__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Request *)
     protobuf_c_message_unpack (&yoke__interface__v1__request__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__request__free_unpacked
                     (Yoke__Interface__V1__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__authenticate__password__init
                     (Yoke__Interface__V1__Authenticate__Password         *message)
{
  static const Yoke__Interface__V1__Authenticate__Password init_value = YOKE__INTERFACE__V1__AUTHENTICATE__PASSWORD__INIT;
  *message = init_value;
}
void   yoke__interface__v1__authenticate__init
                     (Yoke__Interface__V1__Authenticate         *message)
{
  static const Yoke__Interface__V1__Authenticate init_value = YOKE__INTERFACE__V1__AUTHENTICATE__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__authenticate__get_packed_size
                     (const Yoke__Interface__V1__Authenticate *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__authenticate__pack
                     (const Yoke__Interface__V1__Authenticate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__authenticate__pack_to_buffer
                     (const Yoke__Interface__V1__Authenticate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Authenticate *
       yoke__interface__v1__authenticate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Authenticate *)
     protobuf_c_message_unpack (&yoke__interface__v1__authenticate__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__authenticate__free_unpacked
                     (Yoke__Interface__V1__Authenticate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__authenticate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__read__init
                     (Yoke__Interface__V1__Read         *message)
{
  static const Yoke__Interface__V1__Read init_value = YOKE__INTERFACE__V1__READ__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__read__get_packed_size
                     (const Yoke__Interface__V1__Read *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__read__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__read__pack
                     (const Yoke__Interface__V1__Read *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__read__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__read__pack_to_buffer
                     (const Yoke__Interface__V1__Read *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__read__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Read *
       yoke__interface__v1__read__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Read *)
     protobuf_c_message_unpack (&yoke__interface__v1__read__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__read__free_unpacked
                     (Yoke__Interface__V1__Read *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__read__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__subscribe__init
                     (Yoke__Interface__V1__Subscribe         *message)
{
  static const Yoke__Interface__V1__Subscribe init_value = YOKE__INTERFACE__V1__SUBSCRIBE__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__subscribe__get_packed_size
                     (const Yoke__Interface__V1__Subscribe *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribe__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__subscribe__pack
                     (const Yoke__Interface__V1__Subscribe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribe__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__subscribe__pack_to_buffer
                     (const Yoke__Interface__V1__Subscribe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribe__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Subscribe *
       yoke__interface__v1__subscribe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Subscribe *)
     protobuf_c_message_unpack (&yoke__interface__v1__subscribe__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__subscribe__free_unpacked
                     (Yoke__Interface__V1__Subscribe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__subscribe__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__confirm__init
                     (Yoke__Interface__V1__Confirm         *message)
{
  static const Yoke__Interface__V1__Confirm init_value = YOKE__INTERFACE__V1__CONFIRM__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__confirm__get_packed_size
                     (const Yoke__Interface__V1__Confirm *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__confirm__pack
                     (const Yoke__Interface__V1__Confirm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__confirm__pack_to_buffer
                     (const Yoke__Interface__V1__Confirm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Confirm *
       yoke__interface__v1__confirm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Confirm *)
     protobuf_c_message_unpack (&yoke__interface__v1__confirm__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__confirm__free_unpacked
                     (Yoke__Interface__V1__Confirm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__confirm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__command__init
                     (Yoke__Interface__V1__Command         *message)
{
  static const Yoke__Interface__V1__Command init_value = YOKE__INTERFACE__V1__COMMAND__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__command__get_packed_size
                     (const Yoke__Interface__V1__Command *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__command__pack
                     (const Yoke__Interface__V1__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__command__pack_to_buffer
                     (const Yoke__Interface__V1__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Command *
       yoke__interface__v1__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Command *)
     protobuf_c_message_unpack (&yoke__interface__v1__command__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__command__free_unpacked
                     (Yoke__Interface__V1__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__question__init
                     (Yoke__Interface__V1__Question         *message)
{
  static const Yoke__Interface__V1__Question init_value = YOKE__INTERFACE__V1__QUESTION__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__question__get_packed_size
                     (const Yoke__Interface__V1__Question *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__question__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__question__pack
                     (const Yoke__Interface__V1__Question *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__question__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__question__pack_to_buffer
                     (const Yoke__Interface__V1__Question *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__question__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Question *
       yoke__interface__v1__question__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Question *)
     protobuf_c_message_unpack (&yoke__interface__v1__question__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__question__free_unpacked
                     (Yoke__Interface__V1__Question *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__question__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__unit_stream__init
                     (Yoke__Interface__V1__UnitStream         *message)
{
  static const Yoke__Interface__V1__UnitStream init_value = YOKE__INTERFACE__V1__UNIT_STREAM__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__unit_stream__get_packed_size
                     (const Yoke__Interface__V1__UnitStream *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__unit_stream__pack
                     (const Yoke__Interface__V1__UnitStream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__unit_stream__pack_to_buffer
                     (const Yoke__Interface__V1__UnitStream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__UnitStream *
       yoke__interface__v1__unit_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__UnitStream *)
     protobuf_c_message_unpack (&yoke__interface__v1__unit_stream__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__unit_stream__free_unpacked
                     (Yoke__Interface__V1__UnitStream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__unit_stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__stream_release__init
                     (Yoke__Interface__V1__StreamRelease         *message)
{
  static const Yoke__Interface__V1__StreamRelease init_value = YOKE__INTERFACE__V1__STREAM_RELEASE__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__stream_release__get_packed_size
                     (const Yoke__Interface__V1__StreamRelease *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_release__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__stream_release__pack
                     (const Yoke__Interface__V1__StreamRelease *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_release__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__stream_release__pack_to_buffer
                     (const Yoke__Interface__V1__StreamRelease *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__stream_release__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__StreamRelease *
       yoke__interface__v1__stream_release__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__StreamRelease *)
     protobuf_c_message_unpack (&yoke__interface__v1__stream_release__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__stream_release__free_unpacked
                     (Yoke__Interface__V1__StreamRelease *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__stream_release__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__reclaim__init
                     (Yoke__Interface__V1__Reclaim         *message)
{
  static const Yoke__Interface__V1__Reclaim init_value = YOKE__INTERFACE__V1__RECLAIM__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__reclaim__get_packed_size
                     (const Yoke__Interface__V1__Reclaim *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaim__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__reclaim__pack
                     (const Yoke__Interface__V1__Reclaim *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaim__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__reclaim__pack_to_buffer
                     (const Yoke__Interface__V1__Reclaim *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaim__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Reclaim *
       yoke__interface__v1__reclaim__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Reclaim *)
     protobuf_c_message_unpack (&yoke__interface__v1__reclaim__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__reclaim__free_unpacked
                     (Yoke__Interface__V1__Reclaim *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__reclaim__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__response__init
                     (Yoke__Interface__V1__Response         *message)
{
  static const Yoke__Interface__V1__Response init_value = YOKE__INTERFACE__V1__RESPONSE__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__response__get_packed_size
                     (const Yoke__Interface__V1__Response *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__response__pack
                     (const Yoke__Interface__V1__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__response__pack_to_buffer
                     (const Yoke__Interface__V1__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Response *
       yoke__interface__v1__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Response *)
     protobuf_c_message_unpack (&yoke__interface__v1__response__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__response__free_unpacked
                     (Yoke__Interface__V1__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__authenticated__init
                     (Yoke__Interface__V1__Authenticated         *message)
{
  static const Yoke__Interface__V1__Authenticated init_value = YOKE__INTERFACE__V1__AUTHENTICATED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__authenticated__get_packed_size
                     (const Yoke__Interface__V1__Authenticated *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticated__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__authenticated__pack
                     (const Yoke__Interface__V1__Authenticated *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticated__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__authenticated__pack_to_buffer
                     (const Yoke__Interface__V1__Authenticated *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__authenticated__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Authenticated *
       yoke__interface__v1__authenticated__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Authenticated *)
     protobuf_c_message_unpack (&yoke__interface__v1__authenticated__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__authenticated__free_unpacked
                     (Yoke__Interface__V1__Authenticated *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__authenticated__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__subscribed__init
                     (Yoke__Interface__V1__Subscribed         *message)
{
  static const Yoke__Interface__V1__Subscribed init_value = YOKE__INTERFACE__V1__SUBSCRIBED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__subscribed__get_packed_size
                     (const Yoke__Interface__V1__Subscribed *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__subscribed__pack
                     (const Yoke__Interface__V1__Subscribed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__subscribed__pack_to_buffer
                     (const Yoke__Interface__V1__Subscribed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__subscribed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Subscribed *
       yoke__interface__v1__subscribed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Subscribed *)
     protobuf_c_message_unpack (&yoke__interface__v1__subscribed__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__subscribed__free_unpacked
                     (Yoke__Interface__V1__Subscribed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__subscribed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__confirmed__init
                     (Yoke__Interface__V1__Confirmed         *message)
{
  static const Yoke__Interface__V1__Confirmed init_value = YOKE__INTERFACE__V1__CONFIRMED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__confirmed__get_packed_size
                     (const Yoke__Interface__V1__Confirmed *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirmed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__confirmed__pack
                     (const Yoke__Interface__V1__Confirmed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirmed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__confirmed__pack_to_buffer
                     (const Yoke__Interface__V1__Confirmed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__confirmed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Confirmed *
       yoke__interface__v1__confirmed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Confirmed *)
     protobuf_c_message_unpack (&yoke__interface__v1__confirmed__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__confirmed__free_unpacked
                     (Yoke__Interface__V1__Confirmed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__confirmed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__acknowledged__init
                     (Yoke__Interface__V1__Acknowledged         *message)
{
  static const Yoke__Interface__V1__Acknowledged init_value = YOKE__INTERFACE__V1__ACKNOWLEDGED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__acknowledged__get_packed_size
                     (const Yoke__Interface__V1__Acknowledged *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__acknowledged__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__acknowledged__pack
                     (const Yoke__Interface__V1__Acknowledged *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__acknowledged__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__acknowledged__pack_to_buffer
                     (const Yoke__Interface__V1__Acknowledged *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__acknowledged__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Acknowledged *
       yoke__interface__v1__acknowledged__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Acknowledged *)
     protobuf_c_message_unpack (&yoke__interface__v1__acknowledged__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__acknowledged__free_unpacked
                     (Yoke__Interface__V1__Acknowledged *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__acknowledged__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__answered__init
                     (Yoke__Interface__V1__Answered         *message)
{
  static const Yoke__Interface__V1__Answered init_value = YOKE__INTERFACE__V1__ANSWERED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__answered__get_packed_size
                     (const Yoke__Interface__V1__Answered *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__answered__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__answered__pack
                     (const Yoke__Interface__V1__Answered *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__answered__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__answered__pack_to_buffer
                     (const Yoke__Interface__V1__Answered *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__answered__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Answered *
       yoke__interface__v1__answered__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Answered *)
     protobuf_c_message_unpack (&yoke__interface__v1__answered__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__answered__free_unpacked
                     (Yoke__Interface__V1__Answered *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__answered__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__delivering__init
                     (Yoke__Interface__V1__Delivering         *message)
{
  static const Yoke__Interface__V1__Delivering init_value = YOKE__INTERFACE__V1__DELIVERING__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__delivering__get_packed_size
                     (const Yoke__Interface__V1__Delivering *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__delivering__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__delivering__pack
                     (const Yoke__Interface__V1__Delivering *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__delivering__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__delivering__pack_to_buffer
                     (const Yoke__Interface__V1__Delivering *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__delivering__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Delivering *
       yoke__interface__v1__delivering__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Delivering *)
     protobuf_c_message_unpack (&yoke__interface__v1__delivering__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__delivering__free_unpacked
                     (Yoke__Interface__V1__Delivering *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__delivering__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__released__init
                     (Yoke__Interface__V1__Released         *message)
{
  static const Yoke__Interface__V1__Released init_value = YOKE__INTERFACE__V1__RELEASED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__released__get_packed_size
                     (const Yoke__Interface__V1__Released *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__released__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__released__pack
                     (const Yoke__Interface__V1__Released *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__released__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__released__pack_to_buffer
                     (const Yoke__Interface__V1__Released *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__released__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Released *
       yoke__interface__v1__released__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Released *)
     protobuf_c_message_unpack (&yoke__interface__v1__released__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__released__free_unpacked
                     (Yoke__Interface__V1__Released *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__released__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__reclaimed__init
                     (Yoke__Interface__V1__Reclaimed         *message)
{
  static const Yoke__Interface__V1__Reclaimed init_value = YOKE__INTERFACE__V1__RECLAIMED__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__reclaimed__get_packed_size
                     (const Yoke__Interface__V1__Reclaimed *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaimed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__reclaimed__pack
                     (const Yoke__Interface__V1__Reclaimed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaimed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__reclaimed__pack_to_buffer
                     (const Yoke__Interface__V1__Reclaimed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__reclaimed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Reclaimed *
       yoke__interface__v1__reclaimed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Reclaimed *)
     protobuf_c_message_unpack (&yoke__interface__v1__reclaimed__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__reclaimed__free_unpacked
                     (Yoke__Interface__V1__Reclaimed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__reclaimed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__interface__v1__request__field_descriptors[12] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Request, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authenticate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, authenticate),
    &yoke__interface__v1__authenticate__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, read),
    &yoke__interface__v1__read__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscribe",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, subscribe),
    &yoke__interface__v1__subscribe__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirm",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, confirm),
    &yoke__interface__v1__confirm__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, command),
    &yoke__interface__v1__command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, query),
    &yoke__interface__v1__question__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_start",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, stream_start),
    &yoke__interface__v1__unit_stream__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_stop",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, stream_stop),
    &yoke__interface__v1__unit_stream__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_subscribe",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, stream_subscribe),
    &yoke__interface__v1__unit_stream__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_unsubscribe",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, stream_unsubscribe),
    &yoke__interface__v1__stream_release__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reclaim",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Request, operation_case),
    offsetof(Yoke__Interface__V1__Request, reclaim),
    &yoke__interface__v1__reclaim__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__request__field_indices_by_name[] = {
  1,   /* field[1] = authenticate */
  5,   /* field[5] = command */
  4,   /* field[4] = confirm */
  6,   /* field[6] = query */
  2,   /* field[2] = read */
  11,   /* field[11] = reclaim */
  7,   /* field[7] = stream_start */
  8,   /* field[8] = stream_stop */
  9,   /* field[9] = stream_subscribe */
  10,   /* field[10] = stream_unsubscribe */
  3,   /* field[3] = subscribe */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange yoke__interface__v1__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Request",
  "Request",
  "Yoke__Interface__V1__Request",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Request),
  12,
  yoke__interface__v1__request__field_descriptors,
  yoke__interface__v1__request__field_indices_by_name,
  1,  yoke__interface__v1__request__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__authenticate__password__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Authenticate__Password, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Authenticate__Password, secret),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__authenticate__password__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = secret */
};
static const ProtobufCIntRange yoke__interface__v1__authenticate__password__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__authenticate__password__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Authenticate.Password",
  "Password",
  "Yoke__Interface__V1__Authenticate__Password",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Authenticate__Password),
  2,
  yoke__interface__v1__authenticate__password__field_descriptors,
  yoke__interface__v1__authenticate__password__field_indices_by_name,
  1,  yoke__interface__v1__authenticate__password__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__authenticate__password__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__authenticate__field_descriptors[2] =
{
  {
    "password",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Authenticate, credential_case),
    offsetof(Yoke__Interface__V1__Authenticate, password),
    &yoke__interface__v1__authenticate__password__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__Authenticate, credential_case),
    offsetof(Yoke__Interface__V1__Authenticate, token),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__authenticate__field_indices_by_name[] = {
  0,   /* field[0] = password */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange yoke__interface__v1__authenticate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__authenticate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Authenticate",
  "Authenticate",
  "Yoke__Interface__V1__Authenticate",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Authenticate),
  2,
  yoke__interface__v1__authenticate__field_descriptors,
  yoke__interface__v1__authenticate__field_indices_by_name,
  1,  yoke__interface__v1__authenticate__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__authenticate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__read__field_descriptors[2] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Read, kind),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Read, identity),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__read__field_indices_by_name[] = {
  1,   /* field[1] = identity */
  0,   /* field[0] = kind */
};
static const ProtobufCIntRange yoke__interface__v1__read__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__read__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Read",
  "Read",
  "Yoke__Interface__V1__Read",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Read),
  2,
  yoke__interface__v1__read__field_descriptors,
  yoke__interface__v1__read__field_indices_by_name,
  1,  yoke__interface__v1__read__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__read__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__subscribe__field_descriptors[1] =
{
  {
    "filter",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Subscribe, filter),
    &yoke__interface__v1__filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__subscribe__field_indices_by_name[] = {
  0,   /* field[0] = filter */
};
static const ProtobufCIntRange yoke__interface__v1__subscribe__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__subscribe__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Subscribe",
  "Subscribe",
  "Yoke__Interface__V1__Subscribe",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Subscribe),
  1,
  yoke__interface__v1__subscribe__field_descriptors,
  yoke__interface__v1__subscribe__field_indices_by_name,
  1,  yoke__interface__v1__subscribe__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__subscribe__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__confirm__field_descriptors[2] =
{
  {
    "subscription",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Confirm, subscription),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Confirm, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__confirm__field_indices_by_name[] = {
  1,   /* field[1] = sequence */
  0,   /* field[0] = subscription */
};
static const ProtobufCIntRange yoke__interface__v1__confirm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__confirm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Confirm",
  "Confirm",
  "Yoke__Interface__V1__Confirm",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Confirm),
  2,
  yoke__interface__v1__confirm__field_descriptors,
  yoke__interface__v1__confirm__field_indices_by_name,
  1,  yoke__interface__v1__confirm__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__confirm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__command__field_descriptors[3] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Command, unit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Command, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Command, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__command__field_indices_by_name[] = {
  2,   /* field[2] = payload */
  1,   /* field[1] = type */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange yoke__interface__v1__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Command",
  "Command",
  "Yoke__Interface__V1__Command",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Command),
  3,
  yoke__interface__v1__command__field_descriptors,
  yoke__interface__v1__command__field_indices_by_name,
  1,  yoke__interface__v1__command__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__question__field_descriptors[3] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Question, unit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Question, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Question, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__question__field_indices_by_name[] = {
  2,   /* field[2] = payload */
  1,   /* field[1] = type */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange yoke__interface__v1__question__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__question__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Question",
  "Question",
  "Yoke__Interface__V1__Question",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Question),
  3,
  yoke__interface__v1__question__field_descriptors,
  yoke__interface__v1__question__field_indices_by_name,
  1,  yoke__interface__v1__question__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__question__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__unit_stream__field_descriptors[2] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitStream, unit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitStream, stream),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__unit_stream__field_indices_by_name[] = {
  1,   /* field[1] = stream */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange yoke__interface__v1__unit_stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__unit_stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.UnitStream",
  "UnitStream",
  "Yoke__Interface__V1__UnitStream",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__UnitStream),
  2,
  yoke__interface__v1__unit_stream__field_descriptors,
  yoke__interface__v1__unit_stream__field_indices_by_name,
  1,  yoke__interface__v1__unit_stream__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__unit_stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__stream_release__field_descriptors[1] =
{
  {
    "delivery",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__StreamRelease, delivery),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__stream_release__field_indices_by_name[] = {
  0,   /* field[0] = delivery */
};
static const ProtobufCIntRange yoke__interface__v1__stream_release__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__stream_release__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.StreamRelease",
  "StreamRelease",
  "Yoke__Interface__V1__StreamRelease",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__StreamRelease),
  1,
  yoke__interface__v1__stream_release__field_descriptors,
  yoke__interface__v1__stream_release__field_indices_by_name,
  1,  yoke__interface__v1__stream_release__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__stream_release__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define yoke__interface__v1__reclaim__field_descriptors NULL
#define yoke__interface__v1__reclaim__field_indices_by_name NULL
#define yoke__interface__v1__reclaim__number_ranges NULL
const ProtobufCMessageDescriptor yoke__interface__v1__reclaim__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Reclaim",
  "Reclaim",
  "Yoke__Interface__V1__Reclaim",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Reclaim),
  0,
  yoke__interface__v1__reclaim__field_descriptors,
  yoke__interface__v1__reclaim__field_indices_by_name,
  0,  yoke__interface__v1__reclaim__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__reclaim__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__response__field_descriptors[11] =
{
  {
    "authenticate",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, authenticate),
    &yoke__interface__v1__authenticated__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, read),
    &yoke__interface__v1__records__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subscribe",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, subscribe),
    &yoke__interface__v1__subscribed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, confirm),
    &yoke__interface__v1__confirmed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, command),
    &yoke__interface__v1__acknowledged__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, query),
    &yoke__interface__v1__answered__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_start",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, stream_start),
    &yoke__interface__v1__acknowledged__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_stop",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, stream_stop),
    &yoke__interface__v1__acknowledged__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_subscribe",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, stream_subscribe),
    &yoke__interface__v1__delivering__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_unsubscribe",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, stream_unsubscribe),
    &yoke__interface__v1__released__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reclaim",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Response, answer_case),
    offsetof(Yoke__Interface__V1__Response, reclaim),
    &yoke__interface__v1__reclaimed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__response__field_indices_by_name[] = {
  0,   /* field[0] = authenticate */
  4,   /* field[4] = command */
  3,   /* field[3] = confirm */
  5,   /* field[5] = query */
  1,   /* field[1] = read */
  10,   /* field[10] = reclaim */
  6,   /* field[6] = stream_start */
  7,   /* field[7] = stream_stop */
  8,   /* field[8] = stream_subscribe */
  9,   /* field[9] = stream_unsubscribe */
  2,   /* field[2] = subscribe */
};
static const ProtobufCIntRange yoke__interface__v1__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Response",
  "Response",
  "Yoke__Interface__V1__Response",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Response),
  11,
  yoke__interface__v1__response__field_descriptors,
  yoke__interface__v1__response__field_indices_by_name,
  1,  yoke__interface__v1__response__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__authenticated__field_descriptors[3] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Authenticated, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Authenticated, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expires",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Authenticated, expires),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__authenticated__field_indices_by_name[] = {
  0,   /* field[0] = account */
  2,   /* field[2] = expires */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange yoke__interface__v1__authenticated__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__authenticated__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Authenticated",
  "Authenticated",
  "Yoke__Interface__V1__Authenticated",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Authenticated),
  3,
  yoke__interface__v1__authenticated__field_descriptors,
  yoke__interface__v1__authenticated__field_indices_by_name,
  1,  yoke__interface__v1__authenticated__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__authenticated__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__subscribed__field_descriptors[3] =
{
  {
    "snapshot",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Subscribed, carries_case),
    offsetof(Yoke__Interface__V1__Subscribed, snapshot),
    &yoke__interface__v1__snapshot__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Subscribed, carries_case),
    offsetof(Yoke__Interface__V1__Subscribed, event),
    &yoke__interface__v1__event__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overflow",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Subscribed, carries_case),
    offsetof(Yoke__Interface__V1__Subscribed, overflow),
    &yoke__interface__v1__snapshot__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__subscribed__field_indices_by_name[] = {
  1,   /* field[1] = event */
  2,   /* field[2] = overflow */
  0,   /* field[0] = snapshot */
};
static const ProtobufCIntRange yoke__interface__v1__subscribed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__subscribed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Subscribed",
  "Subscribed",
  "Yoke__Interface__V1__Subscribed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Subscribed),
  3,
  yoke__interface__v1__subscribed__field_descriptors,
  yoke__interface__v1__subscribed__field_indices_by_name,
  1,  yoke__interface__v1__subscribed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__subscribed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define yoke__interface__v1__confirmed__field_descriptors NULL
#define yoke__interface__v1__confirmed__field_indices_by_name NULL
#define yoke__interface__v1__confirmed__number_ranges NULL
const ProtobufCMessageDescriptor yoke__interface__v1__confirmed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Confirmed",
  "Confirmed",
  "Yoke__Interface__V1__Confirmed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Confirmed),
  0,
  yoke__interface__v1__confirmed__field_descriptors,
  yoke__interface__v1__confirmed__field_indices_by_name,
  0,  yoke__interface__v1__confirmed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__confirmed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yoke__interface__v1__acknowledged__outcome__enum_values_by_number[4] =
{
  { "OUTCOME_UNSPECIFIED", "YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_UNSPECIFIED", 0 },
  { "OUTCOME_ACCEPTED", "YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_DONE", "YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_DONE", 2 },
  { "OUTCOME_FAILED", "YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_FAILED", 3 },
};
static const ProtobufCIntRange yoke__interface__v1__acknowledged__outcome__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex yoke__interface__v1__acknowledged__outcome__enum_values_by_name[4] =
{
  { "OUTCOME_ACCEPTED", 1 },
  { "OUTCOME_DONE", 2 },
  { "OUTCOME_FAILED", 3 },
  { "OUTCOME_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor yoke__interface__v1__acknowledged__outcome__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Acknowledged.Outcome",
  "Outcome",
  "Yoke__Interface__V1__Acknowledged__Outcome",
  "yoke.interface.v1",
  4,
  yoke__interface__v1__acknowledged__outcome__enum_values_by_number,
  4,
  yoke__interface__v1__acknowledged__outcome__enum_values_by_name,
  1,
  yoke__interface__v1__acknowledged__outcome__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__acknowledged__field_descriptors[2] =
{
  {
    "outcome",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Acknowledged, outcome),
    &yoke__interface__v1__acknowledged__outcome__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Acknowledged, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__acknowledged__field_indices_by_name[] = {
  1,   /* field[1] = line */
  0,   /* field[0] = outcome */
};
static const ProtobufCIntRange yoke__interface__v1__acknowledged__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__acknowledged__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Acknowledged",
  "Acknowledged",
  "Yoke__Interface__V1__Acknowledged",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Acknowledged),
  2,
  yoke__interface__v1__acknowledged__field_descriptors,
  yoke__interface__v1__acknowledged__field_indices_by_name,
  1,  yoke__interface__v1__acknowledged__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__acknowledged__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__answered__field_descriptors[1] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Answered, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__answered__field_indices_by_name[] = {
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange yoke__interface__v1__answered__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__answered__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Answered",
  "Answered",
  "Yoke__Interface__V1__Answered",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Answered),
  1,
  yoke__interface__v1__answered__field_descriptors,
  yoke__interface__v1__answered__field_indices_by_name,
  1,  yoke__interface__v1__answered__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__answered__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__delivering__field_descriptors[5] =
{
  {
    "delivery",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Delivering, delivery),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "socket",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__Delivering, arrives_case),
    offsetof(Yoke__Interface__V1__Delivering, socket),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connection",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Yoke__Interface__V1__Delivering, arrives_case),
    offsetof(Yoke__Interface__V1__Delivering, connection),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__Delivering, arrives_case),
    offsetof(Yoke__Interface__V1__Delivering, path),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowing",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Delivering, flowing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__delivering__field_indices_by_name[] = {
  2,   /* field[2] = connection */
  0,   /* field[0] = delivery */
  4,   /* field[4] = flowing */
  3,   /* field[3] = path */
  1,   /* field[1] = socket */
};
static const ProtobufCIntRange yoke__interface__v1__delivering__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__delivering__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Delivering",
  "Delivering",
  "Yoke__Interface__V1__Delivering",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Delivering),
  5,
  yoke__interface__v1__delivering__field_descriptors,
  yoke__interface__v1__delivering__field_indices_by_name,
  1,  yoke__interface__v1__delivering__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__delivering__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define yoke__interface__v1__released__field_descriptors NULL
#define yoke__interface__v1__released__field_indices_by_name NULL
#define yoke__interface__v1__released__number_ranges NULL
const ProtobufCMessageDescriptor yoke__interface__v1__released__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Released",
  "Released",
  "Yoke__Interface__V1__Released",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Released),
  0,
  yoke__interface__v1__released__field_descriptors,
  yoke__interface__v1__released__field_indices_by_name,
  0,  yoke__interface__v1__released__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__released__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__reclaimed__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Reclaimed, channel),
    &yoke__interface__v1__channel_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "changed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Reclaimed, changed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__reclaimed__field_indices_by_name[] = {
  1,   /* field[1] = changed */
  0,   /* field[0] = channel */
};
static const ProtobufCIntRange yoke__interface__v1__reclaimed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__reclaimed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Reclaimed",
  "Reclaimed",
  "Yoke__Interface__V1__Reclaimed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Reclaimed),
  2,
  yoke__interface__v1__reclaimed__field_descriptors,
  yoke__interface__v1__reclaimed__field_indices_by_name,
  1,  yoke__interface__v1__reclaimed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__reclaimed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
