/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/operations.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2foperations_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2foperations_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"
#include "yoke/interface/v1/events.pb-c.h"
#include "yoke/interface/v1/records.pb-c.h"

typedef struct Yoke__Interface__V1__Request Yoke__Interface__V1__Request;
typedef struct Yoke__Interface__V1__Authenticate Yoke__Interface__V1__Authenticate;
typedef struct Yoke__Interface__V1__Authenticate__Password Yoke__Interface__V1__Authenticate__Password;
typedef struct Yoke__Interface__V1__Read Yoke__Interface__V1__Read;
typedef struct Yoke__Interface__V1__Subscribe Yoke__Interface__V1__Subscribe;
typedef struct Yoke__Interface__V1__Confirm Yoke__Interface__V1__Confirm;
typedef struct Yoke__Interface__V1__Command Yoke__Interface__V1__Command;
typedef struct Yoke__Interface__V1__Question Yoke__Interface__V1__Question;
typedef struct Yoke__Interface__V1__UnitStream Yoke__Interface__V1__UnitStream;
typedef struct Yoke__Interface__V1__StreamRelease Yoke__Interface__V1__StreamRelease;
typedef struct Yoke__Interface__V1__Reclaim Yoke__Interface__V1__Reclaim;
typedef struct Yoke__Interface__V1__Response Yoke__Interface__V1__Response;
typedef struct Yoke__Interface__V1__Authenticated Yoke__Interface__V1__Authenticated;
typedef struct Yoke__Interface__V1__Subscribed Yoke__Interface__V1__Subscribed;
typedef struct Yoke__Interface__V1__Confirmed Yoke__Interface__V1__Confirmed;
typedef struct Yoke__Interface__V1__Acknowledged Yoke__Interface__V1__Acknowledged;
typedef struct Yoke__Interface__V1__Answered Yoke__Interface__V1__Answered;
typedef struct Yoke__Interface__V1__Delivering Yoke__Interface__V1__Delivering;
typedef struct Yoke__Interface__V1__Released Yoke__Interface__V1__Released;
typedef struct Yoke__Interface__V1__Reclaimed Yoke__Interface__V1__Reclaimed;


/* --- enums --- */

typedef enum _Yoke__Interface__V1__Acknowledged__Outcome {
  YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_UNSPECIFIED = 0,
  YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_ACCEPTED = 1,
  YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_DONE = 2,
  YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_FAILED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME)
} Yoke__Interface__V1__Acknowledged__Outcome;

/* --- messages --- */

typedef enum {
  YOKE__INTERFACE__V1__REQUEST__OPERATION__NOT_SET = 0,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_AUTHENTICATE = 2,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_READ = 3,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_SUBSCRIBE = 4,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_CONFIRM = 5,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_COMMAND = 6,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_QUERY = 7,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_STREAM_START = 8,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_STREAM_STOP = 9,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_STREAM_SUBSCRIBE = 10,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_STREAM_UNSUBSCRIBE = 11,
  YOKE__INTERFACE__V1__REQUEST__OPERATION_RECLAIM = 12
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__REQUEST__OPERATION__CASE)
} Yoke__Interface__V1__Request__OperationCase;

struct  Yoke__Interface__V1__Request
{
  ProtobufCMessage base;
  /*
   * The contract's version, checked on every request.
   */
  uint32_t version;
  Yoke__Interface__V1__Request__OperationCase operation_case;
  union {
    Yoke__Interface__V1__Authenticate *authenticate;
    Yoke__Interface__V1__Read *read;
    Yoke__Interface__V1__Subscribe *subscribe;
    Yoke__Interface__V1__Confirm *confirm;
    Yoke__Interface__V1__Command *command;
    Yoke__Interface__V1__Question *query;
    Yoke__Interface__V1__UnitStream *stream_start;
    Yoke__Interface__V1__UnitStream *stream_stop;
    Yoke__Interface__V1__UnitStream *stream_subscribe;
    Yoke__Interface__V1__StreamRelease *stream_unsubscribe;
    Yoke__Interface__V1__Reclaim *reclaim;
  };
};
#define YOKE__INTERFACE__V1__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__request__descriptor) \
    , 0, YOKE__INTERFACE__V1__REQUEST__OPERATION__NOT_SET, {0} }


struct  Yoke__Interface__V1__Authenticate__Password
{
  ProtobufCMessage base;
  char *account;
  char *secret;
};
#define YOKE__INTERFACE__V1__AUTHENTICATE__PASSWORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__authenticate__password__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  YOKE__INTERFACE__V1__AUTHENTICATE__CREDENTIAL__NOT_SET = 0,
  YOKE__INTERFACE__V1__AUTHENTICATE__CREDENTIAL_PASSWORD = 1,
  YOKE__INTERFACE__V1__AUTHENTICATE__CREDENTIAL_TOKEN = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__AUTHENTICATE__CREDENTIAL__CASE)
} Yoke__Interface__V1__Authenticate__CredentialCase;

/*
 * What establishes the caller on a channel whose class requires it: an account and its secret, asked of
 * the host, or a session token already issued on this channel.
 */
struct  Yoke__Interface__V1__Authenticate
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Authenticate__CredentialCase credential_case;
  union {
    Yoke__Interface__V1__Authenticate__Password *password;
    char *token;
  };
};
#define YOKE__INTERFACE__V1__AUTHENTICATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__authenticate__descriptor) \
    , YOKE__INTERFACE__V1__AUTHENTICATE__CREDENTIAL__NOT_SET, {0} }


/*
 * A subject kind, and an identity where one is named: with none, every subject of that kind this
 * channel observes.
 */
struct  Yoke__Interface__V1__Read
{
  ProtobufCMessage base;
  char *kind;
  char *identity;
};
#define YOKE__INTERFACE__V1__READ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__read__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Yoke__Interface__V1__Subscribe
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Filter *filter;
};
#define YOKE__INTERFACE__V1__SUBSCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__subscribe__descriptor) \
    , NULL }


/*
 * I am current as of this sequence, on this subscription.
 */
struct  Yoke__Interface__V1__Confirm
{
  ProtobufCMessage base;
  /*
   * The call identity of the subscription confirmed.
   */
  char *subscription;
  uint64_t sequence;
};
#define YOKE__INTERFACE__V1__CONFIRM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__confirm__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * An instruction for a unit, opaque to the Core and bounded at 1 MiB.
 */
struct  Yoke__Interface__V1__Command
{
  ProtobufCMessage base;
  char *unit;
  char *type;
  ProtobufCBinaryData payload;
};
#define YOKE__INTERFACE__V1__COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__command__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL} }


/*
 * A question for a unit, opaque to the Core and bounded at 1 MiB.
 */
struct  Yoke__Interface__V1__Question
{
  ProtobufCMessage base;
  char *unit;
  char *type;
  ProtobufCBinaryData payload;
};
#define YOKE__INTERFACE__V1__QUESTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__question__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL} }


struct  Yoke__Interface__V1__UnitStream
{
  ProtobufCMessage base;
  char *unit;
  char *stream;
};
#define YOKE__INTERFACE__V1__UNIT_STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__unit_stream__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Yoke__Interface__V1__StreamRelease
{
  ProtobufCMessage base;
  /*
   * The delivery stream.subscribe answered with.
   */
  char *delivery;
};
#define YOKE__INTERFACE__V1__STREAM_RELEASE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__stream_release__descriptor) \
    , (char *)protobuf_c_empty_string }


/*
 * Take control back, on a channel bound as a local socket.
 */
struct  Yoke__Interface__V1__Reclaim
{
  ProtobufCMessage base;
};
#define YOKE__INTERFACE__V1__RECLAIM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__reclaim__descriptor) \
     }


typedef enum {
  YOKE__INTERFACE__V1__RESPONSE__ANSWER__NOT_SET = 0,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_AUTHENTICATE = 1,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_READ = 2,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_SUBSCRIBE = 3,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_CONFIRM = 4,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_COMMAND = 5,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_QUERY = 6,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_STREAM_START = 7,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_STREAM_STOP = 8,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_STREAM_SUBSCRIBE = 9,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_STREAM_UNSUBSCRIBE = 10,
  YOKE__INTERFACE__V1__RESPONSE__ANSWER_RECLAIM = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__RESPONSE__ANSWER__CASE)
} Yoke__Interface__V1__Response__AnswerCase;

struct  Yoke__Interface__V1__Response
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Response__AnswerCase answer_case;
  union {
    Yoke__Interface__V1__Authenticated *authenticate;
    Yoke__Interface__V1__Records *read;
    Yoke__Interface__V1__Subscribed *subscribe;
    Yoke__Interface__V1__Confirmed *confirm;
    Yoke__Interface__V1__Acknowledged *command;
    Yoke__Interface__V1__Answered *query;
    Yoke__Interface__V1__Acknowledged *stream_start;
    Yoke__Interface__V1__Acknowledged *stream_stop;
    Yoke__Interface__V1__Delivering *stream_subscribe;
    Yoke__Interface__V1__Released *stream_unsubscribe;
    Yoke__Interface__V1__Reclaimed *reclaim;
  };
};
#define YOKE__INTERFACE__V1__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__response__descriptor) \
    , YOKE__INTERFACE__V1__RESPONSE__ANSWER__NOT_SET, {0} }


/*
 * The caller established: the account, and the session token that carries the answer through a session.
 */
struct  Yoke__Interface__V1__Authenticated
{
  ProtobufCMessage base;
  char *account;
  char *token;
  Google__Protobuf__Timestamp *expires;
};
#define YOKE__INTERFACE__V1__AUTHENTICATED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__authenticated__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL }


typedef enum {
  YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES__NOT_SET = 0,
  YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES_SNAPSHOT = 1,
  YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES_EVENT = 2,
  YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES_OVERFLOW = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES__CASE)
} Yoke__Interface__V1__Subscribed__CarriesCase;

/*
 * What a subscription carries: the snapshot it opens with, an event, or an overflow and the fresh
 * snapshot that follows it.
 */
struct  Yoke__Interface__V1__Subscribed
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Subscribed__CarriesCase carries_case;
  union {
    Yoke__Interface__V1__Snapshot *snapshot;
    Yoke__Interface__V1__Event *event;
    Yoke__Interface__V1__Snapshot *overflow;
  };
};
#define YOKE__INTERFACE__V1__SUBSCRIBED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__subscribed__descriptor) \
    , YOKE__INTERFACE__V1__SUBSCRIBED__CARRIES__NOT_SET, {0} }


struct  Yoke__Interface__V1__Confirmed
{
  ProtobufCMessage base;
};
#define YOKE__INTERFACE__V1__CONFIRMED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__confirmed__descriptor) \
     }


/*
 * A unit's acknowledgement, correlated to what it answers.
 */
struct  Yoke__Interface__V1__Acknowledged
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Acknowledged__Outcome outcome;
  char *line;
};
#define YOKE__INTERFACE__V1__ACKNOWLEDGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__acknowledged__descriptor) \
    , YOKE__INTERFACE__V1__ACKNOWLEDGED__OUTCOME__OUTCOME_UNSPECIFIED, (char *)protobuf_c_empty_string }


/*
 * A unit's answer, opaque to the Core and bounded at 1 MiB.
 */
struct  Yoke__Interface__V1__Answered
{
  ProtobufCMessage base;
  ProtobufCBinaryData payload;
};
#define YOKE__INTERFACE__V1__ANSWERED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__answered__descriptor) \
    , {0,NULL} }


typedef enum {
  YOKE__INTERFACE__V1__DELIVERING__ARRIVES__NOT_SET = 0,
  YOKE__INTERFACE__V1__DELIVERING__ARRIVES_SOCKET = 2,
  YOKE__INTERFACE__V1__DELIVERING__ARRIVES_CONNECTION = 3,
  YOKE__INTERFACE__V1__DELIVERING__ARRIVES_PATH = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__DELIVERING__ARRIVES__CASE)
} Yoke__Interface__V1__Delivering__ArrivesCase;

/*
 * Where a stream's data will arrive, which a client never derives, and whether the stream is flowing.
 */
struct  Yoke__Interface__V1__Delivering
{
  ProtobufCMessage base;
  /*
   * The delivery: the subscriber's counter, zero-padded to eight digits.
   */
  char *delivery;
  protobuf_c_boolean flowing;
  Yoke__Interface__V1__Delivering__ArrivesCase arrives_case;
  union {
    /*
     * A per-subscriber socket in the instance's tree, which the client connects to.
     */
    char *socket;
    /*
     * On this connection, as stream deliveries carrying the delivery.
     */
    protobuf_c_boolean connection;
    /*
     * The browser projection's path, upgraded to a binary WebSocket.
     */
    char *path;
  };
};
#define YOKE__INTERFACE__V1__DELIVERING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__delivering__descriptor) \
    , (char *)protobuf_c_empty_string, 0, YOKE__INTERFACE__V1__DELIVERING__ARRIVES__NOT_SET, {0} }


struct  Yoke__Interface__V1__Released
{
  ProtobufCMessage base;
};
#define YOKE__INTERFACE__V1__RELEASED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__released__descriptor) \
     }


/*
 * The channel's state after the recomputation; a reclaim that changed nothing says so.
 */
struct  Yoke__Interface__V1__Reclaimed
{
  ProtobufCMessage base;
  Yoke__Interface__V1__ChannelRecord *channel;
  protobuf_c_boolean changed;
};
#define YOKE__INTERFACE__V1__RECLAIMED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__reclaimed__descriptor) \
    , NULL, 0 }


/* Yoke__Interface__V1__Request methods */
void   yoke__interface__v1__request__init
                     (Yoke__Interface__V1__Request         *message);
size_t yoke__interface__v1__request__get_packed_size
                     (const Yoke__Interface__V1__Request   *message);
size_t yoke__interface__v1__request__pack
                     (const Yoke__Interface__V1__Request   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__request__pack_to_buffer
                     (const Yoke__Interface__V1__Request   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Request *
       yoke__interface__v1__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__request__free_unpacked
                     (Yoke__Interface__V1__Request *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Authenticate__Password methods */
void   yoke__interface__v1__authenticate__password__init
                     (Yoke__Interface__V1__Authenticate__Password         *message);
/* Yoke__Interface__V1__Authenticate methods */
void   yoke__interface__v1__authenticate__init
                     (Yoke__Interface__V1__Authenticate         *message);
size_t yoke__interface__v1__authenticate__get_packed_size
                     (const Yoke__Interface__V1__Authenticate   *message);
size_t yoke__interface__v1__authenticate__pack
                     (const Yoke__Interface__V1__Authenticate   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__authenticate__pack_to_buffer
                     (const Yoke__Interface__V1__Authenticate   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Authenticate *
       yoke__interface__v1__authenticate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__authenticate__free_unpacked
                     (Yoke__Interface__V1__Authenticate *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Read methods */
void   yoke__interface__v1__read__init
                     (Yoke__Interface__V1__Read         *message);
size_t yoke__interface__v1__read__get_packed_size
                     (const Yoke__Interface__V1__Read   *message);
size_t yoke__interface__v1__read__pack
                     (const Yoke__Interface__V1__Read   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__read__pack_to_buffer
                     (const Yoke__Interface__V1__Read   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Read *
       yoke__interface__v1__read__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__read__free_unpacked
                     (Yoke__Interface__V1__Read *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Subscribe methods */
void   yoke__interface__v1__subscribe__init
                     (Yoke__Interface__V1__Subscribe         *message);
size_t yoke__interface__v1__subscribe__get_packed_size
                     (const Yoke__Interface__V1__Subscribe   *message);
size_t yoke__interface__v1__subscribe__pack
                     (const Yoke__Interface__V1__Subscribe   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__subscribe__pack_to_buffer
                     (const Yoke__Interface__V1__Subscribe   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Subscribe *
       yoke__interface__v1__subscribe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__subscribe__free_unpacked
                     (Yoke__Interface__V1__Subscribe *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Confirm methods */
void   yoke__interface__v1__confirm__init
                     (Yoke__Interface__V1__Confirm         *message);
size_t yoke__interface__v1__confirm__get_packed_size
                     (const Yoke__Interface__V1__Confirm   *message);
size_t yoke__interface__v1__confirm__pack
                     (const Yoke__Interface__V1__Confirm   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__confirm__pack_to_buffer
                     (const Yoke__Interface__V1__Confirm   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Confirm *
       yoke__interface__v1__confirm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__confirm__free_unpacked
                     (Yoke__Interface__V1__Confirm *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Command methods */
void   yoke__interface__v1__command__init
                     (Yoke__Interface__V1__Command         *message);
size_t yoke__interface__v1__command__get_packed_size
                     (const Yoke__Interface__V1__Command   *message);
size_t yoke__interface__v1__command__pack
                     (const Yoke__Interface__V1__Command   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__command__pack_to_buffer
                     (const Yoke__Interface__V1__Command   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Command *
       yoke__interface__v1__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__command__free_unpacked
                     (Yoke__Interface__V1__Command *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Question methods */
void   yoke__interface__v1__question__init
                     (Yoke__Interface__V1__Question         *message);
size_t yoke__interface__v1__question__get_packed_size
                     (const Yoke__Interface__V1__Question   *message);
size_t yoke__interface__v1__question__pack
                     (const Yoke__Interface__V1__Question   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__question__pack_to_buffer
                     (const Yoke__Interface__V1__Question   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Question *
       yoke__interface__v1__question__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__question__free_unpacked
                     (Yoke__Interface__V1__Question *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__UnitStream methods */
void   yoke__interface__v1__unit_stream__init
                     (Yoke__Interface__V1__UnitStream         *message);
size_t yoke__interface__v1__unit_stream__get_packed_size
                     (const Yoke__Interface__V1__UnitStream   *message);
size_t yoke__interface__v1__unit_stream__pack
                     (const Yoke__Interface__V1__UnitStream   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__unit_stream__pack_to_buffer
                     (const Yoke__Interface__V1__UnitStream   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__UnitStream *
       yoke__interface__v1__unit_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__unit_stream__free_unpacked
                     (Yoke__Interface__V1__UnitStream *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__StreamRelease methods */
void   yoke__interface__v1__stream_release__init
                     (Yoke__Interface__V1__StreamRelease         *message);
size_t yoke__interface__v1__stream_release__get_packed_size
                     (const Yoke__Interface__V1__StreamRelease   *message);
size_t yoke__interface__v1__stream_release__pack
                     (const Yoke__Interface__V1__StreamRelease   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__stream_release__pack_to_buffer
                     (const Yoke__Interface__V1__StreamRelease   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__StreamRelease *
       yoke__interface__v1__stream_release__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__stream_release__free_unpacked
                     (Yoke__Interface__V1__StreamRelease *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Reclaim methods */
void   yoke__interface__v1__reclaim__init
                     (Yoke__Interface__V1__Reclaim         *message);
size_t yoke__interface__v1__reclaim__get_packed_size
                     (const Yoke__Interface__V1__Reclaim   *message);
size_t yoke__interface__v1__reclaim__pack
                     (const Yoke__Interface__V1__Reclaim   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__reclaim__pack_to_buffer
                     (const Yoke__Interface__V1__Reclaim   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Reclaim *
       yoke__interface__v1__reclaim__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__reclaim__free_unpacked
                     (Yoke__Interface__V1__Reclaim *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Response methods */
void   yoke__interface__v1__response__init
                     (Yoke__Interface__V1__Response         *message);
size_t yoke__interface__v1__response__get_packed_size
                     (const Yoke__Interface__V1__Response   *message);
size_t yoke__interface__v1__response__pack
                     (const Yoke__Interface__V1__Response   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__response__pack_to_buffer
                     (const Yoke__Interface__V1__Response   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Response *
       yoke__interface__v1__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__response__free_unpacked
                     (Yoke__Interface__V1__Response *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Authenticated methods */
void   yoke__interface__v1__authenticated__init
                     (Yoke__Interface__V1__Authenticated         *message);
size_t yoke__interface__v1__authenticated__get_packed_size
                     (const Yoke__Interface__V1__Authenticated   *message);
size_t yoke__interface__v1__authenticated__pack
                     (const Yoke__Interface__V1__Authenticated   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__authenticated__pack_to_buffer
                     (const Yoke__Interface__V1__Authenticated   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Authenticated *
       yoke__interface__v1__authenticated__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__authenticated__free_unpacked
                     (Yoke__Interface__V1__Authenticated *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Subscribed methods */
void   yoke__interface__v1__subscribed__init
                     (Yoke__Interface__V1__Subscribed         *message);
size_t yoke__interface__v1__subscribed__get_packed_size
                     (const Yoke__Interface__V1__Subscribed   *message);
size_t yoke__interface__v1__subscribed__pack
                     (const Yoke__Interface__V1__Subscribed   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__subscribed__pack_to_buffer
                     (const Yoke__Interface__V1__Subscribed   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Subscribed *
       yoke__interface__v1__subscribed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__subscribed__free_unpacked
                     (Yoke__Interface__V1__Subscribed *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Confirmed methods */
void   yoke__interface__v1__confirmed__init
                     (Yoke__Interface__V1__Confirmed         *message);
size_t yoke__interface__v1__confirmed__get_packed_size
                     (const Yoke__Interface__V1__Confirmed   *message);
size_t yoke__interface__v1__confirmed__pack
                     (const Yoke__Interface__V1__Confirmed   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__confirmed__pack_to_buffer
                     (const Yoke__Interface__V1__Confirmed   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Confirmed *
       yoke__interface__v1__confirmed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__confirmed__free_unpacked
                     (Yoke__Interface__V1__Confirmed *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Acknowledged methods */
void   yoke__interface__v1__acknowledged__init
                     (Yoke__Interface__V1__Acknowledged         *message);
size_t yoke__interface__v1__acknowledged__get_packed_size
                     (const Yoke__Interface__V1__Acknowledged   *message);
size_t yoke__interface__v1__acknowledged__pack
                     (const Yoke__Interface__V1__Acknowledged   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__acknowledged__pack_to_buffer
                     (const Yoke__Interface__V1__Acknowledged   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Acknowledged *
       yoke__interface__v1__acknowledged__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__acknowledged__free_unpacked
                     (Yoke__Interface__V1__Acknowledged *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Answered methods */
void   yoke__interface__v1__answered__init
                     (Yoke__Interface__V1__Answered         *message);
size_t yoke__interface__v1__answered__get_packed_size
                     (const Yoke__Interface__V1__Answered   *message);
size_t yoke__interface__v1__answered__pack
                     (const Yoke__Interface__V1__Answered   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__answered__pack_to_buffer
                     (const Yoke__Interface__V1__Answered   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Answered *
       yoke__interface__v1__answered__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__answered__free_unpacked
                     (Yoke__Interface__V1__Answered *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Delivering methods */
void   yoke__interface__v1__delivering__init
                     (Yoke__Interface__V1__Delivering         *message);
size_t yoke__interface__v1__delivering__get_packed_size
                     (const Yoke__Interface__V1__Delivering   *message);
size_t yoke__interface__v1__delivering__pack
                     (const Yoke__Interface__V1__Delivering   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__delivering__pack_to_buffer
                     (const Yoke__Interface__V1__Delivering   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Delivering *
       yoke__interface__v1__delivering__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__delivering__free_unpacked
                     (Yoke__Interface__V1__Delivering *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Released methods */
void   yoke__interface__v1__released__init
                     (Yoke__Interface__V1__Released         *message);
size_t yoke__interface__v1__released__get_packed_size
                     (const Yoke__Interface__V1__Released   *message);
size_t yoke__interface__v1__released__pack
                     (const Yoke__Interface__V1__Released   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__released__pack_to_buffer
                     (const Yoke__Interface__V1__Released   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Released *
       yoke__interface__v1__released__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__released__free_unpacked
                     (Yoke__Interface__V1__Released *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Reclaimed methods */
void   yoke__interface__v1__reclaimed__init
                     (Yoke__Interface__V1__Reclaimed         *message);
size_t yoke__interface__v1__reclaimed__get_packed_size
                     (const Yoke__Interface__V1__Reclaimed   *message);
size_t yoke__interface__v1__reclaimed__pack
                     (const Yoke__Interface__V1__Reclaimed   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__reclaimed__pack_to_buffer
                     (const Yoke__Interface__V1__Reclaimed   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Reclaimed *
       yoke__interface__v1__reclaimed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__reclaimed__free_unpacked
                     (Yoke__Interface__V1__Reclaimed *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Interface__V1__Request_Closure)
                 (const Yoke__Interface__V1__Request *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Authenticate__Password_Closure)
                 (const Yoke__Interface__V1__Authenticate__Password *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Authenticate_Closure)
                 (const Yoke__Interface__V1__Authenticate *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Read_Closure)
                 (const Yoke__Interface__V1__Read *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Subscribe_Closure)
                 (const Yoke__Interface__V1__Subscribe *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Confirm_Closure)
                 (const Yoke__Interface__V1__Confirm *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Command_Closure)
                 (const Yoke__Interface__V1__Command *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Question_Closure)
                 (const Yoke__Interface__V1__Question *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__UnitStream_Closure)
                 (const Yoke__Interface__V1__UnitStream *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__StreamRelease_Closure)
                 (const Yoke__Interface__V1__StreamRelease *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Reclaim_Closure)
                 (const Yoke__Interface__V1__Reclaim *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Response_Closure)
                 (const Yoke__Interface__V1__Response *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Authenticated_Closure)
                 (const Yoke__Interface__V1__Authenticated *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Subscribed_Closure)
                 (const Yoke__Interface__V1__Subscribed *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Confirmed_Closure)
                 (const Yoke__Interface__V1__Confirmed *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Acknowledged_Closure)
                 (const Yoke__Interface__V1__Acknowledged *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Answered_Closure)
                 (const Yoke__Interface__V1__Answered *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Delivering_Closure)
                 (const Yoke__Interface__V1__Delivering *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Released_Closure)
                 (const Yoke__Interface__V1__Released *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Reclaimed_Closure)
                 (const Yoke__Interface__V1__Reclaimed *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__interface__v1__request__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__authenticate__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__authenticate__password__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__read__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__subscribe__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__confirm__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__command__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__question__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__unit_stream__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__stream_release__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__reclaim__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__response__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__authenticated__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__subscribed__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__confirmed__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__acknowledged__descriptor;
extern const ProtobufCEnumDescriptor    yoke__interface__v1__acknowledged__outcome__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__answered__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__delivering__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__released__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__reclaimed__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2foperations_2eproto__INCLUDED */
