/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/records.proto */

#ifndef PROTOBUF_C_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED
#define PROTOBUF_C_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Yoke__Interface__V1__Record Yoke__Interface__V1__Record;
typedef struct Yoke__Interface__V1__InstanceRecord Yoke__Interface__V1__InstanceRecord;
typedef struct Yoke__Interface__V1__UnitRecord Yoke__Interface__V1__UnitRecord;
typedef struct Yoke__Interface__V1__UnitRecord__Declared Yoke__Interface__V1__UnitRecord__Declared;
typedef struct Yoke__Interface__V1__UnitRecord__Observed Yoke__Interface__V1__UnitRecord__Observed;
typedef struct Yoke__Interface__V1__UnitRecord__Addressed Yoke__Interface__V1__UnitRecord__Addressed;
typedef struct Yoke__Interface__V1__Condition Yoke__Interface__V1__Condition;
typedef struct Yoke__Interface__V1__ChannelRecord Yoke__Interface__V1__ChannelRecord;
typedef struct Yoke__Interface__V1__ChannelRecord__Declared Yoke__Interface__V1__ChannelRecord__Declared;
typedef struct Yoke__Interface__V1__ChannelRecord__Observed Yoke__Interface__V1__ChannelRecord__Observed;
typedef struct Yoke__Interface__V1__Snapshot Yoke__Interface__V1__Snapshot;
typedef struct Yoke__Interface__V1__Records Yoke__Interface__V1__Records;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  YOKE__INTERFACE__V1__RECORD__SUBJECT__NOT_SET = 0,
  YOKE__INTERFACE__V1__RECORD__SUBJECT_INSTANCE = 1,
  YOKE__INTERFACE__V1__RECORD__SUBJECT_UNIT = 2,
  YOKE__INTERFACE__V1__RECORD__SUBJECT_CHANNEL = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOKE__INTERFACE__V1__RECORD__SUBJECT__CASE)
} Yoke__Interface__V1__Record__SubjectCase;

struct  Yoke__Interface__V1__Record
{
  ProtobufCMessage base;
  Yoke__Interface__V1__Record__SubjectCase subject_case;
  union {
    Yoke__Interface__V1__InstanceRecord *instance;
    Yoke__Interface__V1__UnitRecord *unit;
    Yoke__Interface__V1__ChannelRecord *channel;
  };
};
#define YOKE__INTERFACE__V1__RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__record__descriptor) \
    , YOKE__INTERFACE__V1__RECORD__SUBJECT__NOT_SET, {0} }


struct  Yoke__Interface__V1__InstanceRecord
{
  ProtobufCMessage base;
  protobuf_c_boolean ready;
  protobuf_c_boolean stopping;
  Google__Protobuf__Timestamp *since;
};
#define YOKE__INTERFACE__V1__INSTANCE_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__instance_record__descriptor) \
    , 0, 0, NULL }


struct  Yoke__Interface__V1__UnitRecord__Declared
{
  ProtobufCMessage base;
  char *identity;
  /*
   * plugin, oneshot or interface.
   */
  char *kind;
};
#define YOKE__INTERFACE__V1__UNIT_RECORD__DECLARED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__unit_record__declared__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Yoke__Interface__V1__UnitRecord__Observed
{
  ProtobufCMessage base;
  char *state;
  uint64_t incarnation;
  /*
   * The moment of the last transition.
   */
  Google__Protobuf__Timestamp *since;
  /*
   * None where the unit has never reported.
   */
  Yoke__Interface__V1__Condition *condition;
  /*
   * The streams currently activated.
   */
  size_t n_streams;
  char **streams;
};
#define YOKE__INTERFACE__V1__UNIT_RECORD__OBSERVED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__unit_record__observed__descriptor) \
    , (char *)protobuf_c_empty_string, 0, NULL, NULL, 0,NULL }


/*
 * What a channel may address on a Plugin unit: the objects its plugin was granted. Empty on any other.
 */
struct  Yoke__Interface__V1__UnitRecord__Addressed
{
  ProtobufCMessage base;
  size_t n_streams;
  char **streams;
  size_t n_commands;
  char **commands;
  size_t n_queries;
  char **queries;
};
#define YOKE__INTERFACE__V1__UNIT_RECORD__ADDRESSED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__unit_record__addressed__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  Yoke__Interface__V1__UnitRecord
{
  ProtobufCMessage base;
  Yoke__Interface__V1__UnitRecord__Declared *declared;
  Yoke__Interface__V1__UnitRecord__Observed *observed;
  Yoke__Interface__V1__UnitRecord__Addressed *addressed;
};
#define YOKE__INTERFACE__V1__UNIT_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__unit_record__descriptor) \
    , NULL, NULL, NULL }


/*
 * A unit's own account of how well it is.
 */
struct  Yoke__Interface__V1__Condition
{
  ProtobufCMessage base;
  uint32_t grade;
  char *line;
  Google__Protobuf__Timestamp *since;
};
#define YOKE__INTERFACE__V1__CONDITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__condition__descriptor) \
    , 0, (char *)protobuf_c_empty_string, NULL }


struct  Yoke__Interface__V1__ChannelRecord__Declared
{
  ProtobufCMessage base;
  char *name;
  /*
   * local or http+ws.
   */
  char *projection;
  /*
   * local-socket, loopback or routable.
   */
  char *address_class;
  /*
   * single or multiple.
   */
  char *clients;
};
#define YOKE__INTERFACE__V1__CHANNEL_RECORD__DECLARED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__channel_record__declared__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Yoke__Interface__V1__ChannelRecord__Observed
{
  ProtobufCMessage base;
  protobuf_c_boolean attached;
  /*
   * The client the channel established; unestablished where its class establishes none.
   */
  char *client;
  protobuf_c_boolean suspended;
  /*
   * read-only or dark, while suspended.
   */
  char *grade;
  /*
   * The channel that prevails, while suspended.
   */
  char *by;
  /*
   * Why it was suspended.
   */
  char *reason;
};
#define YOKE__INTERFACE__V1__CHANNEL_RECORD__OBSERVED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__channel_record__observed__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * The channel the record is read on: a channel observes only its own.
 */
struct  Yoke__Interface__V1__ChannelRecord
{
  ProtobufCMessage base;
  Yoke__Interface__V1__ChannelRecord__Declared *declared;
  Yoke__Interface__V1__ChannelRecord__Observed *observed;
};
#define YOKE__INTERFACE__V1__CHANNEL_RECORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__channel_record__descriptor) \
    , NULL, NULL }


/*
 * The current value of every level a filter selects, taken at a sequence: the stream that follows
 * begins at the next.
 */
struct  Yoke__Interface__V1__Snapshot
{
  ProtobufCMessage base;
  uint64_t at;
  size_t n_records;
  Yoke__Interface__V1__Record **records;
};
#define YOKE__INTERFACE__V1__SNAPSHOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__snapshot__descriptor) \
    , 0, 0,NULL }


/*
 * A read's answer: the snapshot's records, and nothing follows.
 */
struct  Yoke__Interface__V1__Records
{
  ProtobufCMessage base;
  size_t n_records;
  Yoke__Interface__V1__Record **records;
};
#define YOKE__INTERFACE__V1__RECORDS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&yoke__interface__v1__records__descriptor) \
    , 0,NULL }


/* Yoke__Interface__V1__Record methods */
void   yoke__interface__v1__record__init
                     (Yoke__Interface__V1__Record         *message);
size_t yoke__interface__v1__record__get_packed_size
                     (const Yoke__Interface__V1__Record   *message);
size_t yoke__interface__v1__record__pack
                     (const Yoke__Interface__V1__Record   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__record__pack_to_buffer
                     (const Yoke__Interface__V1__Record   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Record *
       yoke__interface__v1__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__record__free_unpacked
                     (Yoke__Interface__V1__Record *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__InstanceRecord methods */
void   yoke__interface__v1__instance_record__init
                     (Yoke__Interface__V1__InstanceRecord         *message);
size_t yoke__interface__v1__instance_record__get_packed_size
                     (const Yoke__Interface__V1__InstanceRecord   *message);
size_t yoke__interface__v1__instance_record__pack
                     (const Yoke__Interface__V1__InstanceRecord   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__instance_record__pack_to_buffer
                     (const Yoke__Interface__V1__InstanceRecord   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__InstanceRecord *
       yoke__interface__v1__instance_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__instance_record__free_unpacked
                     (Yoke__Interface__V1__InstanceRecord *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__UnitRecord__Declared methods */
void   yoke__interface__v1__unit_record__declared__init
                     (Yoke__Interface__V1__UnitRecord__Declared         *message);
/* Yoke__Interface__V1__UnitRecord__Observed methods */
void   yoke__interface__v1__unit_record__observed__init
                     (Yoke__Interface__V1__UnitRecord__Observed         *message);
/* Yoke__Interface__V1__UnitRecord__Addressed methods */
void   yoke__interface__v1__unit_record__addressed__init
                     (Yoke__Interface__V1__UnitRecord__Addressed         *message);
/* Yoke__Interface__V1__UnitRecord methods */
void   yoke__interface__v1__unit_record__init
                     (Yoke__Interface__V1__UnitRecord         *message);
size_t yoke__interface__v1__unit_record__get_packed_size
                     (const Yoke__Interface__V1__UnitRecord   *message);
size_t yoke__interface__v1__unit_record__pack
                     (const Yoke__Interface__V1__UnitRecord   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__unit_record__pack_to_buffer
                     (const Yoke__Interface__V1__UnitRecord   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__UnitRecord *
       yoke__interface__v1__unit_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__unit_record__free_unpacked
                     (Yoke__Interface__V1__UnitRecord *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Condition methods */
void   yoke__interface__v1__condition__init
                     (Yoke__Interface__V1__Condition         *message);
size_t yoke__interface__v1__condition__get_packed_size
                     (const Yoke__Interface__V1__Condition   *message);
size_t yoke__interface__v1__condition__pack
                     (const Yoke__Interface__V1__Condition   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__condition__pack_to_buffer
                     (const Yoke__Interface__V1__Condition   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Condition *
       yoke__interface__v1__condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__condition__free_unpacked
                     (Yoke__Interface__V1__Condition *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__ChannelRecord__Declared methods */
void   yoke__interface__v1__channel_record__declared__init
                     (Yoke__Interface__V1__ChannelRecord__Declared         *message);
/* Yoke__Interface__V1__ChannelRecord__Observed methods */
void   yoke__interface__v1__channel_record__observed__init
                     (Yoke__Interface__V1__ChannelRecord__Observed         *message);
/* Yoke__Interface__V1__ChannelRecord methods */
void   yoke__interface__v1__channel_record__init
                     (Yoke__Interface__V1__ChannelRecord         *message);
size_t yoke__interface__v1__channel_record__get_packed_size
                     (const Yoke__Interface__V1__ChannelRecord   *message);
size_t yoke__interface__v1__channel_record__pack
                     (const Yoke__Interface__V1__ChannelRecord   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__channel_record__pack_to_buffer
                     (const Yoke__Interface__V1__ChannelRecord   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__ChannelRecord *
       yoke__interface__v1__channel_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__channel_record__free_unpacked
                     (Yoke__Interface__V1__ChannelRecord *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Snapshot methods */
void   yoke__interface__v1__snapshot__init
                     (Yoke__Interface__V1__Snapshot         *message);
size_t yoke__interface__v1__snapshot__get_packed_size
                     (const Yoke__Interface__V1__Snapshot   *message);
size_t yoke__interface__v1__snapshot__pack
                     (const Yoke__Interface__V1__Snapshot   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__snapshot__pack_to_buffer
                     (const Yoke__Interface__V1__Snapshot   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Snapshot *
       yoke__interface__v1__snapshot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__snapshot__free_unpacked
                     (Yoke__Interface__V1__Snapshot *message,
                      ProtobufCAllocator *allocator);
/* Yoke__Interface__V1__Records methods */
void   yoke__interface__v1__records__init
                     (Yoke__Interface__V1__Records         *message);
size_t yoke__interface__v1__records__get_packed_size
                     (const Yoke__Interface__V1__Records   *message);
size_t yoke__interface__v1__records__pack
                     (const Yoke__Interface__V1__Records   *message,
                      uint8_t             *out);
size_t yoke__interface__v1__records__pack_to_buffer
                     (const Yoke__Interface__V1__Records   *message,
                      ProtobufCBuffer     *buffer);
Yoke__Interface__V1__Records *
       yoke__interface__v1__records__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   yoke__interface__v1__records__free_unpacked
                     (Yoke__Interface__V1__Records *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Yoke__Interface__V1__Record_Closure)
                 (const Yoke__Interface__V1__Record *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__InstanceRecord_Closure)
                 (const Yoke__Interface__V1__InstanceRecord *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__UnitRecord__Declared_Closure)
                 (const Yoke__Interface__V1__UnitRecord__Declared *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__UnitRecord__Observed_Closure)
                 (const Yoke__Interface__V1__UnitRecord__Observed *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__UnitRecord__Addressed_Closure)
                 (const Yoke__Interface__V1__UnitRecord__Addressed *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__UnitRecord_Closure)
                 (const Yoke__Interface__V1__UnitRecord *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Condition_Closure)
                 (const Yoke__Interface__V1__Condition *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__ChannelRecord__Declared_Closure)
                 (const Yoke__Interface__V1__ChannelRecord__Declared *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__ChannelRecord__Observed_Closure)
                 (const Yoke__Interface__V1__ChannelRecord__Observed *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__ChannelRecord_Closure)
                 (const Yoke__Interface__V1__ChannelRecord *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Snapshot_Closure)
                 (const Yoke__Interface__V1__Snapshot *message,
                  void *closure_data);
typedef void (*Yoke__Interface__V1__Records_Closure)
                 (const Yoke__Interface__V1__Records *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor yoke__interface__v1__record__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__instance_record__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__declared__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__observed__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__addressed__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__condition__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__declared__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__observed__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__snapshot__descriptor;
extern const ProtobufCMessageDescriptor yoke__interface__v1__records__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED */
