/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yoke/interface/v1/records.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yoke/interface/v1/records.pb-c.h"
void   yoke__interface__v1__record__init
                     (Yoke__Interface__V1__Record         *message)
{
  static const Yoke__Interface__V1__Record init_value = YOKE__INTERFACE__V1__RECORD__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__record__get_packed_size
                     (const Yoke__Interface__V1__Record *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__record__pack
                     (const Yoke__Interface__V1__Record *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__record__pack_to_buffer
                     (const Yoke__Interface__V1__Record *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Record *
       yoke__interface__v1__record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Record *)
     protobuf_c_message_unpack (&yoke__interface__v1__record__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__record__free_unpacked
                     (Yoke__Interface__V1__Record *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__instance_record__init
                     (Yoke__Interface__V1__InstanceRecord         *message)
{
  static const Yoke__Interface__V1__InstanceRecord init_value = YOKE__INTERFACE__V1__INSTANCE_RECORD__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__instance_record__get_packed_size
                     (const Yoke__Interface__V1__InstanceRecord *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__instance_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__instance_record__pack
                     (const Yoke__Interface__V1__InstanceRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__instance_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__instance_record__pack_to_buffer
                     (const Yoke__Interface__V1__InstanceRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__instance_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__InstanceRecord *
       yoke__interface__v1__instance_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__InstanceRecord *)
     protobuf_c_message_unpack (&yoke__interface__v1__instance_record__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__instance_record__free_unpacked
                     (Yoke__Interface__V1__InstanceRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__instance_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__unit_record__declared__init
                     (Yoke__Interface__V1__UnitRecord__Declared         *message)
{
  static const Yoke__Interface__V1__UnitRecord__Declared init_value = YOKE__INTERFACE__V1__UNIT_RECORD__DECLARED__INIT;
  *message = init_value;
}
void   yoke__interface__v1__unit_record__observed__init
                     (Yoke__Interface__V1__UnitRecord__Observed         *message)
{
  static const Yoke__Interface__V1__UnitRecord__Observed init_value = YOKE__INTERFACE__V1__UNIT_RECORD__OBSERVED__INIT;
  *message = init_value;
}
void   yoke__interface__v1__unit_record__addressed__init
                     (Yoke__Interface__V1__UnitRecord__Addressed         *message)
{
  static const Yoke__Interface__V1__UnitRecord__Addressed init_value = YOKE__INTERFACE__V1__UNIT_RECORD__ADDRESSED__INIT;
  *message = init_value;
}
void   yoke__interface__v1__unit_record__init
                     (Yoke__Interface__V1__UnitRecord         *message)
{
  static const Yoke__Interface__V1__UnitRecord init_value = YOKE__INTERFACE__V1__UNIT_RECORD__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__unit_record__get_packed_size
                     (const Yoke__Interface__V1__UnitRecord *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__unit_record__pack
                     (const Yoke__Interface__V1__UnitRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__unit_record__pack_to_buffer
                     (const Yoke__Interface__V1__UnitRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__unit_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__UnitRecord *
       yoke__interface__v1__unit_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__UnitRecord *)
     protobuf_c_message_unpack (&yoke__interface__v1__unit_record__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__unit_record__free_unpacked
                     (Yoke__Interface__V1__UnitRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__unit_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__condition__init
                     (Yoke__Interface__V1__Condition         *message)
{
  static const Yoke__Interface__V1__Condition init_value = YOKE__INTERFACE__V1__CONDITION__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__condition__get_packed_size
                     (const Yoke__Interface__V1__Condition *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__condition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__condition__pack
                     (const Yoke__Interface__V1__Condition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__condition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__condition__pack_to_buffer
                     (const Yoke__Interface__V1__Condition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__condition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Condition *
       yoke__interface__v1__condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Condition *)
     protobuf_c_message_unpack (&yoke__interface__v1__condition__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__condition__free_unpacked
                     (Yoke__Interface__V1__Condition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__condition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__channel_record__declared__init
                     (Yoke__Interface__V1__ChannelRecord__Declared         *message)
{
  static const Yoke__Interface__V1__ChannelRecord__Declared init_value = YOKE__INTERFACE__V1__CHANNEL_RECORD__DECLARED__INIT;
  *message = init_value;
}
void   yoke__interface__v1__channel_record__observed__init
                     (Yoke__Interface__V1__ChannelRecord__Observed         *message)
{
  static const Yoke__Interface__V1__ChannelRecord__Observed init_value = YOKE__INTERFACE__V1__CHANNEL_RECORD__OBSERVED__INIT;
  *message = init_value;
}
void   yoke__interface__v1__channel_record__init
                     (Yoke__Interface__V1__ChannelRecord         *message)
{
  static const Yoke__Interface__V1__ChannelRecord init_value = YOKE__INTERFACE__V1__CHANNEL_RECORD__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__channel_record__get_packed_size
                     (const Yoke__Interface__V1__ChannelRecord *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__channel_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__channel_record__pack
                     (const Yoke__Interface__V1__ChannelRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__channel_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__channel_record__pack_to_buffer
                     (const Yoke__Interface__V1__ChannelRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__channel_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__ChannelRecord *
       yoke__interface__v1__channel_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__ChannelRecord *)
     protobuf_c_message_unpack (&yoke__interface__v1__channel_record__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__channel_record__free_unpacked
                     (Yoke__Interface__V1__ChannelRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__channel_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__snapshot__init
                     (Yoke__Interface__V1__Snapshot         *message)
{
  static const Yoke__Interface__V1__Snapshot init_value = YOKE__INTERFACE__V1__SNAPSHOT__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__snapshot__get_packed_size
                     (const Yoke__Interface__V1__Snapshot *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__snapshot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__snapshot__pack
                     (const Yoke__Interface__V1__Snapshot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__snapshot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__snapshot__pack_to_buffer
                     (const Yoke__Interface__V1__Snapshot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__snapshot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Snapshot *
       yoke__interface__v1__snapshot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Snapshot *)
     protobuf_c_message_unpack (&yoke__interface__v1__snapshot__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__snapshot__free_unpacked
                     (Yoke__Interface__V1__Snapshot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__snapshot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yoke__interface__v1__records__init
                     (Yoke__Interface__V1__Records         *message)
{
  static const Yoke__Interface__V1__Records init_value = YOKE__INTERFACE__V1__RECORDS__INIT;
  *message = init_value;
}
size_t yoke__interface__v1__records__get_packed_size
                     (const Yoke__Interface__V1__Records *message)
{
  assert(message->base.descriptor == &yoke__interface__v1__records__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yoke__interface__v1__records__pack
                     (const Yoke__Interface__V1__Records *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yoke__interface__v1__records__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yoke__interface__v1__records__pack_to_buffer
                     (const Yoke__Interface__V1__Records *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yoke__interface__v1__records__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yoke__Interface__V1__Records *
       yoke__interface__v1__records__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yoke__Interface__V1__Records *)
     protobuf_c_message_unpack (&yoke__interface__v1__records__descriptor,
                                allocator, len, data);
}
void   yoke__interface__v1__records__free_unpacked
                     (Yoke__Interface__V1__Records *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yoke__interface__v1__records__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yoke__interface__v1__record__field_descriptors[3] =
{
  {
    "instance",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Record, subject_case),
    offsetof(Yoke__Interface__V1__Record, instance),
    &yoke__interface__v1__instance_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Record, subject_case),
    offsetof(Yoke__Interface__V1__Record, unit),
    &yoke__interface__v1__unit_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Record, subject_case),
    offsetof(Yoke__Interface__V1__Record, channel),
    &yoke__interface__v1__channel_record__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__record__field_indices_by_name[] = {
  2,   /* field[2] = channel */
  0,   /* field[0] = instance */
  1,   /* field[1] = unit */
};
static const ProtobufCIntRange yoke__interface__v1__record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Record",
  "Record",
  "Yoke__Interface__V1__Record",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Record),
  3,
  yoke__interface__v1__record__field_descriptors,
  yoke__interface__v1__record__field_indices_by_name,
  1,  yoke__interface__v1__record__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__instance_record__field_descriptors[3] =
{
  {
    "ready",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__InstanceRecord, ready),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stopping",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__InstanceRecord, stopping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "since",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__InstanceRecord, since),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__instance_record__field_indices_by_name[] = {
  0,   /* field[0] = ready */
  2,   /* field[2] = since */
  1,   /* field[1] = stopping */
};
static const ProtobufCIntRange yoke__interface__v1__instance_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__instance_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.InstanceRecord",
  "InstanceRecord",
  "Yoke__Interface__V1__InstanceRecord",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__InstanceRecord),
  3,
  yoke__interface__v1__instance_record__field_descriptors,
  yoke__interface__v1__instance_record__field_indices_by_name,
  1,  yoke__interface__v1__instance_record__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__instance_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__unit_record__declared__field_descriptors[2] =
{
  {
    "identity",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Declared, identity),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Declared, kind),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__unit_record__declared__field_indices_by_name[] = {
  0,   /* field[0] = identity */
  1,   /* field[1] = kind */
};
static const ProtobufCIntRange yoke__interface__v1__unit_record__declared__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__declared__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.UnitRecord.Declared",
  "Declared",
  "Yoke__Interface__V1__UnitRecord__Declared",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__UnitRecord__Declared),
  2,
  yoke__interface__v1__unit_record__declared__field_descriptors,
  yoke__interface__v1__unit_record__declared__field_indices_by_name,
  1,  yoke__interface__v1__unit_record__declared__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__unit_record__declared__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__unit_record__observed__field_descriptors[5] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, state),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incarnation",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, incarnation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "since",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, since),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "condition",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, condition),
    &yoke__interface__v1__condition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streams",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, n_streams),
    offsetof(Yoke__Interface__V1__UnitRecord__Observed, streams),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__unit_record__observed__field_indices_by_name[] = {
  3,   /* field[3] = condition */
  1,   /* field[1] = incarnation */
  2,   /* field[2] = since */
  0,   /* field[0] = state */
  4,   /* field[4] = streams */
};
static const ProtobufCIntRange yoke__interface__v1__unit_record__observed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__observed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.UnitRecord.Observed",
  "Observed",
  "Yoke__Interface__V1__UnitRecord__Observed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__UnitRecord__Observed),
  5,
  yoke__interface__v1__unit_record__observed__field_descriptors,
  yoke__interface__v1__unit_record__observed__field_indices_by_name,
  1,  yoke__interface__v1__unit_record__observed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__unit_record__observed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__unit_record__addressed__field_descriptors[3] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, n_streams),
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, streams),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commands",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, n_commands),
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, commands),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queries",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, n_queries),
    offsetof(Yoke__Interface__V1__UnitRecord__Addressed, queries),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__unit_record__addressed__field_indices_by_name[] = {
  1,   /* field[1] = commands */
  2,   /* field[2] = queries */
  0,   /* field[0] = streams */
};
static const ProtobufCIntRange yoke__interface__v1__unit_record__addressed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__addressed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.UnitRecord.Addressed",
  "Addressed",
  "Yoke__Interface__V1__UnitRecord__Addressed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__UnitRecord__Addressed),
  3,
  yoke__interface__v1__unit_record__addressed__field_descriptors,
  yoke__interface__v1__unit_record__addressed__field_indices_by_name,
  1,  yoke__interface__v1__unit_record__addressed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__unit_record__addressed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__unit_record__field_descriptors[3] =
{
  {
    "declared",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord, declared),
    &yoke__interface__v1__unit_record__declared__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord, observed),
    &yoke__interface__v1__unit_record__observed__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addressed",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__UnitRecord, addressed),
    &yoke__interface__v1__unit_record__addressed__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__unit_record__field_indices_by_name[] = {
  2,   /* field[2] = addressed */
  0,   /* field[0] = declared */
  1,   /* field[1] = observed */
};
static const ProtobufCIntRange yoke__interface__v1__unit_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__unit_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.UnitRecord",
  "UnitRecord",
  "Yoke__Interface__V1__UnitRecord",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__UnitRecord),
  3,
  yoke__interface__v1__unit_record__field_descriptors,
  yoke__interface__v1__unit_record__field_indices_by_name,
  1,  yoke__interface__v1__unit_record__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__unit_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__condition__field_descriptors[3] =
{
  {
    "grade",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Condition, grade),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Condition, line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "since",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Condition, since),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__condition__field_indices_by_name[] = {
  0,   /* field[0] = grade */
  1,   /* field[1] = line */
  2,   /* field[2] = since */
};
static const ProtobufCIntRange yoke__interface__v1__condition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__condition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Condition",
  "Condition",
  "Yoke__Interface__V1__Condition",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Condition),
  3,
  yoke__interface__v1__condition__field_descriptors,
  yoke__interface__v1__condition__field_indices_by_name,
  1,  yoke__interface__v1__condition__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__condition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__channel_record__declared__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Declared, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "projection",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Declared, projection),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_class",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Declared, address_class),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clients",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Declared, clients),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__channel_record__declared__field_indices_by_name[] = {
  2,   /* field[2] = address_class */
  3,   /* field[3] = clients */
  0,   /* field[0] = name */
  1,   /* field[1] = projection */
};
static const ProtobufCIntRange yoke__interface__v1__channel_record__declared__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__declared__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.ChannelRecord.Declared",
  "Declared",
  "Yoke__Interface__V1__ChannelRecord__Declared",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__ChannelRecord__Declared),
  4,
  yoke__interface__v1__channel_record__declared__field_descriptors,
  yoke__interface__v1__channel_record__declared__field_indices_by_name,
  1,  yoke__interface__v1__channel_record__declared__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__channel_record__declared__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__channel_record__observed__field_descriptors[6] =
{
  {
    "attached",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, attached),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, client),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suspended",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, suspended),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grade",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, grade),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "by",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, by),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reason",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord__Observed, reason),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__channel_record__observed__field_indices_by_name[] = {
  0,   /* field[0] = attached */
  4,   /* field[4] = by */
  1,   /* field[1] = client */
  3,   /* field[3] = grade */
  5,   /* field[5] = reason */
  2,   /* field[2] = suspended */
};
static const ProtobufCIntRange yoke__interface__v1__channel_record__observed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__observed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.ChannelRecord.Observed",
  "Observed",
  "Yoke__Interface__V1__ChannelRecord__Observed",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__ChannelRecord__Observed),
  6,
  yoke__interface__v1__channel_record__observed__field_descriptors,
  yoke__interface__v1__channel_record__observed__field_indices_by_name,
  1,  yoke__interface__v1__channel_record__observed__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__channel_record__observed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__channel_record__field_descriptors[2] =
{
  {
    "declared",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord, declared),
    &yoke__interface__v1__channel_record__declared__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__ChannelRecord, observed),
    &yoke__interface__v1__channel_record__observed__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__channel_record__field_indices_by_name[] = {
  0,   /* field[0] = declared */
  1,   /* field[1] = observed */
};
static const ProtobufCIntRange yoke__interface__v1__channel_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__channel_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.ChannelRecord",
  "ChannelRecord",
  "Yoke__Interface__V1__ChannelRecord",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__ChannelRecord),
  2,
  yoke__interface__v1__channel_record__field_descriptors,
  yoke__interface__v1__channel_record__field_indices_by_name,
  1,  yoke__interface__v1__channel_record__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__channel_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__snapshot__field_descriptors[2] =
{
  {
    "at",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Yoke__Interface__V1__Snapshot, at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "records",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Snapshot, n_records),
    offsetof(Yoke__Interface__V1__Snapshot, records),
    &yoke__interface__v1__record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__snapshot__field_indices_by_name[] = {
  0,   /* field[0] = at */
  1,   /* field[1] = records */
};
static const ProtobufCIntRange yoke__interface__v1__snapshot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__snapshot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Snapshot",
  "Snapshot",
  "Yoke__Interface__V1__Snapshot",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Snapshot),
  2,
  yoke__interface__v1__snapshot__field_descriptors,
  yoke__interface__v1__snapshot__field_indices_by_name,
  1,  yoke__interface__v1__snapshot__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__snapshot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yoke__interface__v1__records__field_descriptors[1] =
{
  {
    "records",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yoke__Interface__V1__Records, n_records),
    offsetof(Yoke__Interface__V1__Records, records),
    &yoke__interface__v1__record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yoke__interface__v1__records__field_indices_by_name[] = {
  0,   /* field[0] = records */
};
static const ProtobufCIntRange yoke__interface__v1__records__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor yoke__interface__v1__records__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "yoke.interface.v1.Records",
  "Records",
  "Yoke__Interface__V1__Records",
  "yoke.interface.v1",
  sizeof(Yoke__Interface__V1__Records),
  1,
  yoke__interface__v1__records__field_descriptors,
  yoke__interface__v1__records__field_indices_by_name,
  1,  yoke__interface__v1__records__number_ranges,
  (ProtobufCMessageInit) yoke__interface__v1__records__init,
  NULL,NULL,NULL    /* reserved[123] */
};
